### ISSUE TITLE
0.0.0.9 Unload 2/3

### ISSUE THREAD

**Issue by Chrxstxph** [loki79uk/FS25_UniversalAutoload#55] opened 2024-12-02 13:38 UTC
Hey
![image](https://github.com/user-attachments/assets/f4e4b145-c21b-4048-93fa-f412143cf966)

Loading is perfect, but when i try to unload just the first two of these tanks are going to be unloaded

**Comment by loki79uk** [comment] 2024-12-02 17:03
Is this reproducible?  Can you turn on the debugging display (CTRL-SHIFT-F12) and take another screenshot?  Also can you attach your mod settings xml so I can try to reproduce exactly.

**Comment by Chrxstxph** [comment] 2024-12-02 20:24
![image](https://github.com/user-attachments/assets/26927a29-7339-482e-bd21-d1ceda58e924)

I only have this console, is that right?
Well, it wasn't really reproducible, charging worked, discharging worked too, everything was discharged, then I wanted to charge it again, but only one of the left ones (the ones I just discharged) was recorded.

Does that help in any way? I hope
UniversalAutoload.xml :
```
<?xml` version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="data/vehicles/krone/profiLiner/profiLiner.xml">
            <configuration selectedConfigs="1"/>
        </vehicle>
        <vehicle configFileName="data/vehicles/farmtech/dpw1800/dpw1800.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.000 1.130 -0.820" width="2.400642" length="9.728786" height="2.403885"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/kroeger/pwo24/pwo24.xml">
            <configuration selectedConfigs="1">
                <loadingArea offset="-0.033 1.276 -0.176" width="2.347353" length="9.772966" height="2.278679"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
`</universalAutoload>

```

**Comment by loki79uk** [comment] 2024-12-02 20:38
This is unrelated, but you should delete all of the lines for the KRONE, as like this it just won't work at all.
i.e. remove all of:
```xml
        <vehicle configFileName="data/vehicles/krone/profiLiner/profiLiner.xml">
            <configuration selectedConfigs="1"/>
        </vehicle>
```

It could be related to the bug I'm working on now: https://github.com/loki79uk/FS25_UniversalAutoload/issues/60

So let me try a few things for that and see if it makes any difference in the next release.

**Comment by loki79uk** [comment] 2024-12-03 22:15
okay, I know what this is now - it is a duplicate of https://github.com/loki79uk/FS25_UniversalAutoload/issues/21

For that vehicle UAL currently cannot tell the difference between the two configurations, so it uses the same size loading zone for both, even though they are not the same size.  So I guess it is using the shorter zone for the longer truck and then it doesn't see the third IBC.
![image](https://github.com/user-attachments/assets/c28e8d36-a408-49fe-b196-db611c1f97e6)
![image](https://github.com/user-attachments/assets/2b35a607-4860-4172-8dcc-1879238e8ced)

**Comment by loki79uk** [comment] 2024-12-04 17:55
Actually, I don't think it can be this anymore, unless you are on an old version.  I tried just now with both styles:
![image](https://github.com/user-attachments/assets/7a0bceae-ef32-4992-94e6-a15cf91fd237)
![image](https://github.com/user-attachments/assets/d6976316-4b72-42cd-9ad9-834463e7771c)
And both are stored correctly in the xml:
![image](https://github.com/user-attachments/assets/6518363a-8f05-4ae9-a46a-a6b083085be1)

and I can load and unload 3x IBC containers:
![image](https://github.com/user-attachments/assets/86e12876-fdee-48b1-b352-9245b1cfc90c)
![image](https://github.com/user-attachments/assets/27a1eb63-ec38-43af-badc-e8d8b129fa4d)

**Comment by loki79uk** [comment] 2024-12-07 00:52
Should be fixed now in latest release (15) https://github.com/loki79uk/FS25_UniversalAutoload/releases

You should find that the old loading zones are forgotten, but you just need to treat them as new vehicles - either buy a new one or configure it in the workshop.  You can safely delete the old configurations (single number id) from your mod settings file.  The new ones will look like `"1|2"`, where 1 is the config set, and 2 is the cab configuration.

**Comment by loki79uk** [comment] 2024-12-08 14:20
Closing as fixed.  If anyone is still having this issue, try deleting the mod settings file and configure again from scratch.

**Closed by loki79uk** 2024-12-08 14:20 UTC
