### ISSUE TITLE
Issue with loading pallets onto flatbed/semitrailer in Universal Autoload for FS25

### ISSUE THREAD

**Issue by AndriuOfficial** [loki79uk/FS25_UniversalAutoload#68] opened 2024-12-03 19:11 UTC
Dear developer,

I have encountered an issue while using the Universal Autoload mod for FS25. When loading pallets onto a flatbed or semitrailer, I’ve noticed that the vehicle tends to “wobble,” even when stationary, and the load shifts or tips over. This happens frequently, making it difficult to manage the loads properly.

I hope you can consider this feedback and, if possible, resolve the issue in a future update of the mod.

Thank you for your work and attention.

Best regards,
Andriu

**Comment by FarmerTreanor** [comment] 2024-12-03 20:25
what correct version sorry as noticed message show use .0.11 then look message says done update

**Comment by loki79uk** [comment] 2024-12-06 00:51
Closing as can't reproduce. Please re-open if you can provide steps to reproduce with the latest version.

**Closed by loki79uk** 2024-12-06 00:51 UTC
