### ISSUE TITLE
Trailer Axle Blocker Mod

### ISSUE THREAD

**Issue by wousje01** [loki79uk/FS25_UniversalAutoload#133] opened 2024-12-14 12:14 UTC
It seems that when you run this mod together with the autoload mod, the Trailer Axle Blocker no longer works properly on the trailers. Do you perhaps see a possibility to include this function in your script?

**Comment by loki79uk** [comment] 2024-12-14 14:19
What is the error?  I helped them fix that script once, so I know about it, but I have not looked at it since FS25.

**Comment by geeknessfr** [comment] 2024-12-14 14:57
> It seems that when you run this mod together with the autoload mod, the Trailer Axle Blocker no longer works properly on the trailers. Do you perhaps see a possibility to include this function in your script?

If you talk about the fact you can't lock axle on bale trailers...

I've also seen that we can't use Axle Blocker on Bale Trailer, but I didn't think it was related to UAL ...
... So I just tested on a new savegame **WITHOUT UAL** ... and I can confirm "Trailer Axle Blocker" just don't work with Bale Trailers...


Working on the 2 first trailers : 
![FarmingSimulator2025Game_xqJQDUZqHW](https://github.com/user-attachments/assets/1a5a99be-38c4-450d-86d4-48b541cfb636)

... but not on the bale trailers...
![FarmingSimulator2025Game_gGG2148FY0](https://github.com/user-attachments/assets/cfb93f47-bbd5-4091-bf2c-1ee0576ba863)

**Comment by wousje01** [comment] 2024-12-14 16:36
Indeed, my apologies. I thought it was related to Autoload, but it seems
that the Farmtech DPW 1800 doesn’t work with the Trailer Axle Blocker,
which is a shame. :) Still, thank you for testing it out and checking, as
well as for your quick response! :)

You're doing great work! :) Do you also have plans in the future to create
production factories, like for example a brewery, etc.?

Op za 14 dec 2024 om 15:57 schreef Geekness ***@***.***>:

**Comment by wousje01** [comment] 2024-12-14 16:37
> > It seems that when you run this mod together with the autoload mod, the Trailer Axle Blocker no longer works properly on the trailers. Do you perhaps see a possibility to include this function in your script?
> 
> If you talk about the fact you can't lock axle on bale trailers...
> 
> I've also seen that we can't use Axle Blocker on Bale Trailer, but I didn't think it was related to UAL ... ... So I just tested on a new savegame **WITHOUT UAL** ... and I can confirm "Trailer Axle Blocker" just don't work with Bale Trailers...
> 
> Working on the 2 first trailers : ![FarmingSimulator2025Game_xqJQDUZqHW](https://private-user-images.githubusercontent.com/28137335/395790104-1a5a99be-38c4-450d-86d4-48b541cfb636.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTQ0NzQsIm5iZiI6MTczNDE5NDE3NCwicGF0aCI6Ii8yODEzNzMzNS8zOTU3OTAxMDQtMWE1YTk5YmUtMzhjNC00NTBkLTg2ZDQtNDhiNTQxY2ZiNjM2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDE2MzYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MTMxZTc3ZjdkZDFmNjM5Zjk2MTliY2Q5ZmRjNWE0N2M5NDljZDRmNzE4MzE2NDgzODViN2RiZTA0NWI2NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sA-kI11RKcAUWpW68LvrxhbDOlnlFH5iZCqFrC-qygM)
> 
> ... but not on bale trailers... ![FarmingSimulator2025Game_gGG2148FY0](https://private-user-images.githubusercontent.com/28137335/395790127-cfb93f47-bbd5-4091-bf2c-1ee0576ba863.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTQ0NzQsIm5iZiI6MTczNDE5NDE3NCwicGF0aCI6Ii8yODEzNzMzNS8zOTU3OTAxMjctY2ZiOTNmNDctYmJkNS00MDkxLWJmMmMtMWVlMDU3NmJhODYzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDE2MzYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiM2JmYTZlYTJhZTVkMmUxYzI1NTM5ODViOTQ1OGE1NzU0YjE1ODcwYTg4OWVkYTNiZWYwODQ2YjUyZDRkN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YceOPZeunh7GZjz6dNGLPr_RpdXZUjkyIKO4IGDt5ME)

Indeed, my apologies. I thought it was related to Autoload, but it seems that the Farmtech DPW 1800 doesn’t work with the Trailer Axle Blocker, which is a shame. :) Still, thank you for testing it out and checking, as well as for your quick response! :)

**Comment by wousje01** [comment] 2024-12-14 16:38
> What is the error? I helped them fix that script once, so I know about it, but I have not looked at it since FS25.

I thought it was related to the script, that the wagon wasn’t working, but luckily it’s not. :)

You're doing great work! :) Do you also have plans in the future to create production factories, like for example a brewery, etc.?

**Comment by loki79uk** [comment] 2024-12-14 17:36
> You're doing great work! :) Do you also have plans in the future to create production factories, like for example a brewery, etc.?

I'm not really interested in making 3d mods.  But any pallets from any mods will automatically be supported by this version of UAL.

**Comment by loki79uk** [comment] 2024-12-14 18:17
Closing as not a bug

**Closed by loki79uk** 2024-12-14 18:17 UTC
