### ISSUE TITLE
Autoloading not working on Demco flatbed or Pro Liner trailers (V 0.2.1.3)

### ISSUE THREAD

**Issue by ComplicatedBreakfast** [loki79uk/FS25_UniversalAutoload#143] opened 2024-12-16 04:13 UTC
Mod was working then stopped, even after server restart. Started off as same issue as before where pallets would only load into a specific area on the trailer, then completely said "unable to load pallets of this size".

**Comment by ComplicatedBreakfast** [comment] 2024-12-16 06:46
**EDIT:** It looks like the mod is working but after about 1-2 auto loads it no longer detects the trailer as being empty after an offload. The weight of the vehicle and trailer remains the same after an offload, we're thinking that something is not actually removing the items physically, only visibly after pressing shift+I.

**Comment by loki79uk** [comment] 2024-12-16 07:40
Can you send me a screenshot with the debugging view active (to see how the zone is configured and how many pallets it thinks are loaded) and also a log file.

**Comment by ComplicatedBreakfast** [comment] 2024-12-16 07:41
Debug view has not worked for me yet

**Comment by loki79uk** [comment] 2024-12-16 07:51
Are you in multiplayer.  You should still get a display in F1 menu of his many pallets it thinks are are loaded. Also in the log anyway.

**Comment by ComplicatedBreakfast** [comment] 2024-12-16 07:52
Yes multiplayer, none of the other guys are also able to get the debug menu to pull up.

**Comment by loki79uk** [comment] 2024-12-16 08:04
In multiplayer it is just an entry at the bottom of the F1 menu, not the full display.  I'll see what I can add, but need to transfer data from the server to clients.  Log file is good enough, can you send the server one?

**Comment by ComplicatedBreakfast** [comment] 2024-12-16 08:10
Here's the log file from the time 
[Log File.txt](https://github.com/user-attachments/files/18146740/Log.File.txt)

**Comment by loki79uk** [comment] 2024-12-16 08:32
I'll have to look this evening now.  There is something about an emergency garbage collection, so maybe the server is low on memory.  How many vehicles do you have with autoload?

**Comment by ComplicatedBreakfast** [comment] 2024-12-16 08:34
RAM usage only shows like 9% of total memory. All users on the server have 1-2 autoload trailers.

**Comment by loki79uk** [comment] 2024-12-16 10:17
Is this when people left on purpose, or something went wrong:
```
2024-12-15 14:32 Warning: Send called with unknown target address.
2024-12-15 14:32 Sir Shabby left the game
```

Also there are loads of these errors that I don't recognise:
```
2024-12-15 14:46 LUA call stack:
  =dataS/scripts/vehicles/Vehicle.lua:1353 delete
  =dataS/scripts/vehicles/VehicleSystem.lua:202 deleteMarkedVehicles
  =dataS/scripts/BaseMission.lua:1142 update
  =dataS/scripts/FSBaseMission.lua:1936 update
  =dataS/scripts/mission00.lua:658 update
  =dataS/scripts/main.lua:1195 update
```

Can you send me the mod settings file from the server?

**Comment by ComplicatedBreakfast** [comment] 2024-12-17 02:53
1: That was someone leaving on purpose

2: I don't know how to get that. Are you asking for the mods folder?

**Comment by loki79uk** [comment] 2024-12-18 10:30
The same "deleteMarkedVehicles" error was reported in lumberjack, but I have no idea how any mods can be causing this..  https://github.com/loki79uk/FS25_LumberJack/issues/36

**Comment by loki79uk** [comment] 2024-12-21 18:59
I don't know about the deleteMarkedVehicles, but the original issue should be fully resolved in latest release.  Suspect a duplicate of #69, but possibly also had corrupted settings saved on the server.

**Closed by loki79uk** 2024-12-21 18:59 UTC
