### ISSUE TITLE
Autoloading when drive

### ISSUE THREAD

**Issue by dexus92** [loki79uk/FS25_UniversalAutoload#162] opened 2024-12-18 19:54 UTC
It is not issue but I don't know where I can add purpose.

Can you add setting to switch "autoload when you drive" (without stop to autoload)?
And start autoload I can drive and pick up bales or pallets and when finish I can end autoload.

**Comment by loki79uk** [comment] 2024-12-18 19:55
It is not possible for pallets, but for bales you can set "Bale Trailer" in the menu and then use bale collection mode (SHIFT-R)

**Comment by dexus92** [comment] 2024-12-18 20:01
Can you show me where is menu with settings on screenshot? :)
I can't see it :(

**Comment by loki79uk** [comment] 2024-12-18 20:09
In the shop, press "A"

**Comment by loki79uk** [comment] 2024-12-20 19:04
Closing as not a bug.  You may have been on an old version or something before the shop menu was added.  Please try with the latest and comment here if you still need assistance.

**Closed by loki79uk** 2024-12-20 19:04 UTC
