### ISSUE TITLE
mo me funciona 

### ISSUE THREAD

**Issue by alex785esp** [loki79uk/FS25_UniversalAutoload#150] opened 2024-12-17 13:17 UTC
![farming 25](https://github.com/user-attachments/assets/8c33dbfb-cb8c-4964-b314-9b09dd428539)
 no me va para cargar ni ninguna funcion y me sale que error de area

**Comment by loki79uk** [comment] 2024-12-17 13:32
Check that your mod settings file is not missing a load area, e.g.: https://github.com/loki79uk/FS25_UniversalAutoload/issues/148#issuecomment-2548368962

**Comment by loki79uk** [comment] 2024-12-20 18:59
Closing as not a bug, but you can still reply here for assistance if you still can't clear the old settings.

**Closed by loki79uk** 2024-12-20 18:59 UTC
