### ISSUE TITLE
Loading continue when trailer is full

### ISSUE THREAD

**Issue by geeknessfr** [loki79uk/FS25_UniversalAutoload#9] opened 2024-11-28 14:33 UTC
I just found a little bug with a DEMCO Steel Drop Deck  and LOT of pallets of eggs ^^

The loading loop to the first position and continue to load some pallets inside others... (5 more here)

- Version 0.0.0.3
- No error in console.
- Didn't try with other pallets yet

Trailer Tested with the bug :
- Steel Drop Deck
- H550 Beavertail

No bug :
- Stema Trius (Car Trailer)

Simple video to show the bug :
https://youtu.be/gj-x89ctcnY

**Comment by iAlreadyExist** [comment] 2024-11-28 14:38
it should be fixed with the latest

**Comment by iAlreadyExist** [comment] 2024-11-28 14:44
are you sure you are with version 0.0.0.3 becouse for me its saying its already full and its not putting more pallets

**Comment by geeknessfr** [comment] 2024-11-28 14:52
> are you sure you are with the latest version 0.0.0.3 becouse for me its saying its already full and its not putting more pallets

Yes, but i don't try to load a second time the trailer here, I just load the trailer and it loops back to the first position.

Same bug with the lowbed trailer (H550 Beavertail) I just bought from the store, with the v0.0.0.3.
But I don't have the bug with the Car Trailer (Stema Trius)


![image](https://github.com/user-attachments/assets/18cfc684-85fd-4587-ac0e-309ebeed25aa)

**Comment by loki79uk** [comment] 2024-11-28 15:47
Could it be only with multi-zone trailers?  Does that fit with your observations?

**Comment by geeknessfr** [comment] 2024-11-28 16:01
> Could it be only with multi-zone trailers? Does that fit with your observations?

Yes, it's a good point and for now I didn't have the bug with a single zone trailer...

I currently tryiing to test with other trailers... and making some other tests to the mod to find bugs... I'll let you know if I found anything else.

**Comment by memmelaar** [comment] 2024-11-28 17:07
i added the mod to my mod folder --when i went in game the mod  was not there to activate

**Comment by geeknessfr** [comment] 2024-11-28 17:24
> i added the mod to my mod folder --when i went in game the mod was not there to activate

I created a new issue for you.

**Comment by memmelaar** [comment] 2024-11-28 17:31
any idea  on why?

**Comment by loki79uk** [comment] 2024-12-01 00:38
> > Could it be only with multi-zone trailers? Does that fit with your observations?
> 
> Yes, it's a good point and for now I didn't have the bug with a single zone trailer...
> 
> I currently tryiing to test with other trailers... and making some other tests to the mod to find bugs... I'll let you know if I find anything else.

I have not forgotten about this one, but I've been too busy with all the multiplayer stuff to look properly.  I really should have released as single player only to start with, but I know people would still try multiplayer and complain it is not working anyway 😅

Anyway, is it any different with the latest version 0.0.0.7, or are you still having trouble with double loading?

**Comment by geeknessfr** [comment] 2024-12-01 01:21
Actually, I was holding off on doing more tests for a bit since I knew you were working on the multiplayer stuff. With all the feedback you’re getting right now, I figured I wouldn’t dive into the smaller, "non-urgent" bugs just yet. 😄
Being a dev myself and having made a bunch of mods for other games, I totally get what it’s like to be laser-focused on one part of development and wanting to nail that before tackling everything else.

That said, I haven’t had the issue since, but I also haven’t been stressing your mod with 150 pallets lately. 😅 Once you’ve tackled the current bugs and multiplayer issues, I’d be happy to give it another “stress test” and dig up all sorts of little bugs for you—if that’s something you’re up for! 😄

Honestly, great job so far. I love your mod, and it’s already working pretty well!

I’ll let you know if the problem pops up again, especially if I manage to find a reliable way to reproduce it.

**Comment by loki79uk** [comment] 2024-12-01 22:15
> Actually, I was holding off on doing more tests for a bit since I knew you were working on the multiplayer stuff. With all the feedback you’re getting right now, I figured I wouldn’t dive into the smaller, "non-urgent" bugs just yet. 😄 Being a dev myself and having made a bunch of mods for other games, I totally get what it’s like to be laser-focused on one part of development and wanting to nail that before tackling everything else.
> 
> That said, I haven’t had the issue since, but I also haven’t been stressing your mod with 150 pallets lately. 😅 Once you’ve tackled the current bugs and multiplayer issues, I’d be happy to give it another “stress test” and dig up all sorts of little bugs for you—if that’s something you’re up for! 😉
> 
> Honestly, great job so far. I love your mod, and it’s already working pretty well!
> 
> I’ll let you know if the problem pops up again, especially if I manage to find a reliable way to reproduce it.

Thanks for understanding!  You are 100% correct.  I think I've finally cracked the MP stuff for now with v0.0.0.8, so please go ahead do your worst now! :D

Main bugs I'm already aware of:
- Unloading is always allowed, so it is very easy to cause disasters by unloading on top of other stuff
- Detection area is bigger than the actual triggers, so some near-by objects are detected as loaded even when they are not
- This multi-zone loading one, but I can't reproduce it - so if you can figure out how that would be great!

**Comment by geeknessfr** [comment] 2024-12-01 23:40
Ok, really nice work for the MP stuff !

I've updated the mod to the v0.0.0.9 right now, so as soon as I found anything I'll let you know !

And, if I can reproduce this loading-loop-thing I'll try to find a way to reproduce it and will try to find why ^^

Thanks !

**Closed** 2024-12-03 21:47 UTC
