### ISSUE TITLE
 Excessive drop on server during pallet transport

### ISSUE THREAD

**Issue by MHMTALP** [loki79uk/FS25_UniversalAutoload#145] opened 2024-12-16 16:59 UTC
Hello

I get excessive drop ping while carrying pallets on the online server, what is the reason?

**Comment by loki79uk** [comment] 2024-12-16 17:14
In FS22 it was like this even in base game, just autload increases the chances that you have a lot of pallets loaded.  Have you tried reloading the same game without UAL active?

**Comment by MHMTALP** [comment] 2024-12-16 17:32
I'm so sorry, what does ual mean?

**Comment by loki79uk** [comment] 2024-12-16 17:33
UAL = UniversalAutoload

**Comment by loki79uk** [comment] 2024-12-18 14:04
Have you tried this without UAL?  You could also zip your savegame and I'll test it on my server.

**Comment by loki79uk** [comment] 2024-12-20 19:02
Closing as not a bug, but you can continue to message on here if the above didn't work.

**Closed by loki79uk** 2024-12-20 19:02 UTC
