### ISSUE TITLE
Unload does not work with multifarmer

### ISSUE THREAD

**Issue by VestalisDE** [loki79uk/FS25_UniversalAutoload#94] opened 2024-12-07 00:07 UTC
Hi guys,

might be an extreme edge case but I just discovered, that I am not able to unload my cargo with a special combination of vehicles:

MERLO Multifamer 44.9 as "tractor" with the Krampe Dolly 10L is not able to unload the KRONE Trailer Profi Liner with salad and egg crates.
As soon as I use the Volva FH16 Truck or my Challenger MT635 with the same dolly it works perfectly.

When in debug it shows the drop-off zone, but it does not work.
Screenshots attached, do not mind the colors due to HDR.
![Farming Simulator 25 Screenshot 2024 12 07 - 00 59 19 20](https://github.com/user-attachments/assets/abbe6133-a81f-4252-af40-e84b8f6fc1bd)
![Farming Simulator 25 Screenshot 2024 12 07 - 01 00 34 37](https://github.com/user-attachments/assets/ab84aa96-abe6-4232-ad46-1d47b8932d8c)

Autoload Version v0.0.0.15
_(reported with v14, but just confirmed again with v15, as it was just released)_

**Comment by loki79uk** [comment] 2024-12-07 00:21
I think you need to select the vechicle with the "G" key.  I can't actually tell because your image is so bright, but it looks like all of the debugging display is all gray which means it is not selected.  If you have multiple UAL trailers connected together, then only the selected one will be active.

**Comment by VestalisDE** [comment] 2024-12-07 01:59
> I think you need to select the vehicle with the "G" key. I can't actually tell because your image is so bright, but it looks like all of the debugging display is gray which means it is not selected. If you have multiple UAL trailers connected together, then only the selected one will be active.

Nope, thats sadly not the issue. With anything else (multifarmer, dolly or anything at the front) then the trailer selected I do not get the debug display at all. 
So its really just due to the HDR image quality, it is the trailer selected.

**Comment by loki79uk** [comment] 2024-12-07 02:03
Okay, I'll try to reproduce this tomorrow.  Thanks for the report!

**Comment by geeknessfr** [comment] 2024-12-07 07:12
So, I’ll try to be as clear as possible because this one is quite tricky!

I managed to reproduce the bug, and I know “why”—or almost—and at least how to **temporarily fix it**. ;)

To reproduce the issue, it happens with the vehicles @VestalisDE mentioned. You load the trailer, and then you can’t unload it because the keybindings don’t show up... (Idk why this happen with this vehicle... but ok...)

![FarmingSimulator2025Game_84BneYLuWW](https://github.com/user-attachments/assets/cb80f10b-61fc-472d-8545-98bbe5f847d8)

_Note : Left Shift-I AND U (to change the unloading side) don't show up._

However... I went into the control settings and changed Left Shift + I to Right Shift + I. After that, the keybindings appeared! (Interestingly, even the U key to switch the unloading side also appeared.)

![FarmingSimulator2025Game_JAvBQnBoBP](https://github.com/user-attachments/assets/4609fc0b-623d-4a61-b146-9f43af87bc35)


**Here’s the "fun" part:** I reverted back to the default Left Shift + I in the settings, and everything worked perfectly... until I detached and reattached the trailer. Then, the keybindings disappeared again. This doesn’t happen with a different key combination. The U key also behaves the same way—it doesn’t show up for this trailer, making it impossible to switch sides.

### **Note:**

- I have the unloading shortcut mapped to my controller. When the default keybinding is set, the controller shortcut doesn’t work either... But it does work if the keyboard shortcut is functioning. (so when it show up on the top left corner)
- The shortcut to switch sides doesn’t work on the keyboard, yet it still works on the controller. ^^

**Temporary Solution** for @VestalisDE (and maybe for your mod, Loki): Change the Left Shift + I shortcut to something else... one that doesn’t magically disappear! ;)

**Comment by loki79uk** [comment] 2024-12-07 10:52
That is some great detective work there!  I will see if I can figure out what is going on.

**Comment by loki79uk** [comment] 2024-12-07 12:03
I made some progress, the key just fails to bind.  The boolean value below is the "valid" return value from 
`valid, actionEventId = self:addActionEvent(spec.actionEvents, ... )`

```
2024-12-07 11:53 updateActionEventKeys: KRONE Trailer Profi Liner - UAL #404962
2024-12-07 11:53   UNLOAD_ALL: false
2024-12-07 11:53   TOGGLE_LOADING: true
2024-12-07 11:53   TOGGLE_FILTER: true
2024-12-07 11:53   TOGGLE_HORIZONTAL: true
2024-12-07 11:53   CYCLE_MATERIAL_FW: true
2024-12-07 11:53   CYCLE_MATERIAL_BW: true
2024-12-07 11:53   SELECT_ALL_MATERIALS: false
2024-12-07 11:53   CYCLE_CONTAINER_FW: true
2024-12-07 11:53   CYCLE_CONTAINER_BW: true
2024-12-07 11:53   SELECT_ALL_CONTAINERS: true
2024-12-07 11:53   TOGGLE_TIPSIDE: true
2024-12-07 11:53   TOGGLE_SHOW_LOADING: true
2024-12-07 11:53   TOGGLE_SHOW_DEBUG: true
2024-12-07 11:53 *** updateActionEventKeys ***
```

**Comment by loki79uk** [comment] 2024-12-07 13:33
This makes no sense..

If I bind to other keys then it works fine:
![image](https://github.com/user-attachments/assets/6082e111-7ac9-446e-bdb2-784a2e0ac110)
![image](https://github.com/user-attachments/assets/52ac30e2-9fee-4fd7-8472-36f8a020e0fb)

**Comment by loki79uk** [comment] 2024-12-07 14:24
I've found it!  The dolly was a red herring, it is the crab steering:

![image](https://github.com/user-attachments/assets/573c1a82-9530-4f9e-b30c-5d4b0f37e8e7)

So there are two options:
1) Everyone has to rebind "crab steering" to something else
2) I can force remove the conflict and use mine, but that could cause issues for some..

_just because you can do something, doesn't always mean you should..._

**Comment by loki79uk** [comment] 2024-12-07 18:39
hopefully fixed now in latest release: https://github.com/loki79uk/FS25_UniversalAutoload/releases

**Comment by FarmerTreanor** [comment] 2024-12-07 19:37
0.0.16 shows as 0.0.15 in moddesc

**Comment by loki79uk** [comment] 2024-12-08 14:29
Closing as fixed.

**Closed by loki79uk** 2024-12-08 14:29 UTC
