### ISSUE TITLE
Loading logs

### ISSUE THREAD

**Issue by WillTechdotBB** [loki79uk/FS25_UniversalAutoload#125] opened 2024-12-13 04:53 UTC
Only one size loads, and it's the smallest size (top of tree). and at times it doesn't even load at all. Using base game log trailer.

**Comment by geeknessfr** [comment] 2024-12-13 05:30
Given the lack of information and no logs.txt, I’m guessing you didn’t resize the loading area when you bought your trailer.

As loki said in v0.2.0.0 :
> You will also have to RESIZE the box yourself. Log trailers are mostly air with no flat surfaces, so it is difficult to find the loading space programatically.

And to resize the loading area, when you buy a trailer :

> TO CONFIGURE LOADING ZONES:
> 
> - Use middle mouse click in the shop to activate editing
> - Right click drag to move individual faces
> - ALT-right click drag to move opposing faces (use this for width)
> - SHIFT-right click drag to move the whole zone
> - CTRL with any of the above for fine control
> - SHIFT-CTRL middle mouse click to auto-calculate the zone from scratch (if you mess up)
> - Configuration can be edited in mod settings XML (if you know what you are doing)

Also, just a thought: you could make the blue box taller than the trailer to let the logs fall into it, and longer to provide enough space for the logs. But be sure to avoid any collisions with the trailer or truck parts, or the logs will clip through the sides.

Have fun !

**Comment by WillTechdotBB** [comment] 2024-12-13 11:03
I did all of that actually. 

 Will try again later and provide the log.

**Comment by coastalwolf** [comment] 2024-12-13 11:19
are you using the most recent version of UAL? 

> I did all of that actually.
> 
> Will try again later and provide the log.
> 
> Quick question, is the mod sorting the logs by size similar like it tries to sort pallets when loading?

are you using the most current version of UAL? most recent is 0.2.1.1.  Also can you show a screen shot of your log trailer in the shop configuration screen?

**Comment by loki79uk** [comment] 2024-12-13 12:53
> Quick question, is the mod sorting the logs by size similar like it tries to sort pallets when loading?

Yes it sorts by length before loading.

**Comment by loki79uk** [comment] 2024-12-17 08:51
Prety sure this is just using an unconfigured log trailer, closing as not a bug.

**Closed by loki79uk** 2024-12-17 08:51 UTC
