### ISSUE TITLE
LodeKing Prestige Super-B rendering issue

### ISSUE THREAD

**Issue by TheMightyMcGrew** [loki79uk/FS25_UniversalAutoload#107] opened 2024-12-09 18:13 UTC
This is on multiplayer with universal autoloader as the only mod on server. Happens when the trailer is purchased from the store as used or new and in any color. As soon as the trailer starts trying to render. Crashes the entire server

**Comment by loki79uk** [comment] 2024-12-09 18:39
Can you attach your log file?

**Comment by TheMightyMcGrew** [comment] 2024-12-09 18:54
> Can you attach your log file?
[log_2024-12-09_18-27.txt](https://github.com/user-attachments/files/18066499/log_2024-12-09_18-27.txt)

Let me know if this file works, i had to copy it by hand from the server host we're using and I dont think github likes nano text files.

**Comment by loki79uk** [comment] 2024-12-09 19:02
I can see the file thanks.  It looks like UAL was fine and then something happened in AttacherJoints.

Unfortunately this is one of the redacted lines from GIANTS... they removed all lines between 1746 to 1992 (see attached).  I don't know why they did that...

```
2024-12-09 18:21 data/vehicles/lodeKing/prestigeSuperBTrailer/prestigeSuperB_front.i3d (27.21 ms)
2024-12-09 18:21 LODE KING Prestige Super-B Pull trailer: UAL - fill volumes (2)
2024-12-09 18:21   [1] = 20200
2024-12-09 18:21   [2] = 20200
2024-12-09 18:21 LODE KING Prestige Super-B Pull trailer: NOT VALID FOR UAL
2024-12-09 18:21 REMOVE EVENT LISTENERS
2024-12-09 18:21 LODE KING Prestige Super-B Pull trailer: UAL - fill volumes (2)
2024-12-09 18:21   [1] = 20200
2024-12-09 18:21   [2] = 20200
2024-12-09 18:21 LODE KING Prestige Super-B Pull trailer: NOT VALID FOR UAL
2024-12-09 18:21 REMOVE EVENT LISTENERS
2024-12-09 18:21 Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/AttacherJoints.lua:1769: attempt to index nil with 'delayedObjectChangesOnAttach'
```
[AttacherJoints.txt](https://github.com/user-attachments/files/18066594/AttacherJoints.txt)

**Comment by loki79uk** [comment] 2024-12-09 19:04
It could be a bug with removing the event listeners - that used to cause problems in FS22 until GIANTS fixed it, but maybe they un-fixed it moving to 25?

**Comment by loki79uk** [comment] 2024-12-11 19:32
Is this reproducible, or did it only happen once?

**Comment by TheMightyMcGrew** [comment] 2024-12-12 14:06
its still actively happening on our server. We are barred from having that particular trailer while we have autoload on the server.

**Comment by TheMightyMcGrew** [comment] 2024-12-12 14:10
The way it works is: Going into the shop GUI and selecting that trailer will cause a client side error in which can be fixed by relogging. Until a relog the shop GUI will not work correctly and the green loading throbber is stuck on any page of any vehicle or purchase you look at. If someone, anyone, tries to BUY that trailer, thats when it crashes the server.

**Comment by loki79uk** [comment] 2024-12-12 14:21
I'm connected to my dedi now and can buy that trailer.  Can you buy it without UAL installed?

![image](https://github.com/user-attachments/assets/978b2284-36e8-4cea-a840-faebfd40267e)
![image](https://github.com/user-attachments/assets/fefa76a0-de8b-4431-a529-11e2198c91d3)
![image](https://github.com/user-attachments/assets/c54c0652-781d-4f14-bec4-289769a3cfba)
![image](https://github.com/user-attachments/assets/9790360f-b8b9-4cfc-8ecb-61f055ca6a30)

**Comment by loki79uk** [comment] 2024-12-13 08:53
Is it possible to try without UAL installed?

**Comment by TheMightyMcGrew** [comment] 2024-12-14 13:17
yes ill try that sometime today or tomorrow when i can get back to the server we're using

**Comment by loki79uk** [comment] 2024-12-16 23:30
Have you found anything new?  I still can't reproduce this.  Does it happen with no mods on the server?

**Comment by TheMightyMcGrew** [comment] 2024-12-17 07:23
Sorry for the wait. I removed the mod this morning and bought the trailer with no issues
![20241217092129_1](https://github.com/user-attachments/assets/1fba09a8-1301-4a04-a1b5-d3354dc0dde5)

**Comment by TheMightyMcGrew** [comment] 2024-12-17 07:58
ok and unfortunately the trailer issue is gone now that Ive reinstalled the mod back onto the server. We can buy the trailer that was causing the issue now and the previous trailers that had autoload seem to be working fine now. Sorry if this was a waste of time man :/

**Comment by loki79uk** [comment] 2024-12-17 08:16
These kind of intermittent errors are the worst.  I can't think of any reason why one specific trailer would fail vs any others, but clearly something was up.  Closing as can't reproduce, but please do re-open or make a new bug if it happens again and maybe we can work out the cause.

**Closed by loki79uk** 2024-12-17 08:16 UTC
