### ISSUE TITLE
Long Pallet loaded off the front of trailer.

### ISSUE THREAD

**Issue by venom4hire** [loki79uk/FS25_UniversalAutoload#43] opened 2024-12-01 14:59 UTC
Happened just now figured I would add a screenshot
![shot](https://github.com/user-attachments/assets/78c4fba5-ebd8-4837-972a-6b731783716d)

**Comment by loki79uk** [comment] 2024-12-01 16:54
Thanks! They should be sorted by size, so I'm not sure what happened there.  I'll try to reproduce it.

**Comment by loki79uk** [comment] 2024-12-03 22:30
I know what happens here - they are sorted by AREA.  This is because at the time of sorting I don't know which side length (i.e. orientation) will be used for loading, and typically the largest area will have the longest side length so it all works out.  I will have a think about how to adjust the packing in edge cases like this.

**Comment by loki79uk** [comment] 2024-12-07 21:15
I've got a few options, but none of them are perfect:

![image](https://github.com/user-attachments/assets/2627b392-2ea8-4836-a942-7c9c097fc073)
![image](https://github.com/user-attachments/assets/a50b7257-2084-4eae-9451-1a37b9f5cbde)
![image](https://github.com/user-attachments/assets/62d94dcd-1522-40ab-9ae1-030292d538ac)

They all improve if you have multiples of each type..  I guess any of those is better than sticking out the front! :D

**Comment by loki79uk** [comment] 2024-12-08 11:02
I have gone with the settings for image1 in the previous post.  Not a huge change, but as with all changes it could have inintended consequences..  Now we always load the things with the longest side first, and if something is loaded later (in a new loading action) that is longer than the previous item on the row, then it will start a new row.

**Comment by loki79uk** [comment] 2024-12-08 11:17
Actually, not even the same as 1. I've forgotten what I was doing last night, but loading with v0.0.0.18 seems better than all of those anyway:
![image](https://github.com/user-attachments/assets/e08ce8e0-ff43-4f86-b6ec-be63b9548867)

**Comment by loki79uk** [comment] 2024-12-08 14:18
Closing as fixed.  Please make a new bug if this change has any unexpected consequences on loading patterns.

**Closed by loki79uk** 2024-12-08 14:18 UTC

**Comment by loki79uk** [comment] 2025-01-14 23:17
I have reverted this change in the latest version as it was interfering with the implementation of the old FS22 loading.  I would be interested to know if you can reproduce it again! https://github.com/loki79uk/FS25_UniversalAutoload/releases

**Comment by venom4hire** [comment] 2025-01-15 00:20
I will definitely try.

**Comment by loki79uk** [comment] 2025-01-19 21:07
I've been messing with this again in my current working version.  Adding a screenshot from testing to refer to later..

![Image](https://github.com/user-attachments/assets/71a32532-fb19-4a64-a143-e384c3e83ba9)
