### ISSUE TITLE
v0.0.0.6 Buttons Don't working

### ISSUE THREAD

**Issue by saeedsg220** [loki79uk/FS25_UniversalAutoload#29] opened 2024-11-30 15:30 UTC
Hi , UniversalAutoload for fs25 v0.0.0.6  : 
fix in shop show menu ui left top  Buttons  but don't working and Loading is not done in single player.

**Comment by loki79uk** [comment] 2024-11-30 16:38
I think I've found the cause of a lot of these issues.  Fix incoming..

**Comment by loki79uk** [comment] 2024-11-30 16:54
Please try v0.0.0.7: https://github.com/loki79uk/FS25_UniversalAutoload/releases

but be aware that new vehicles might still have the issue.  I will fix it tomorrow.

**Comment by Trivium1709** [comment] 2024-11-30 17:01
> Please try v0.0.0.7: https://github.com/loki79uk/FS25_UniversalAutoload/releases
> 
> but be aware that new vehicles might still have the issue. I will fix it tomorrow.

updated but still doesnt work for me on new vehicles or old ones. Also, there's not visual for selecting the next material type, it will always give the error: "no compatible goods are available for loading or unloading"

**Comment by saeedsg220** [comment] 2024-11-30 17:07
Don't be tired.
Our engineer will always help you report problems. Thank you.

**Comment by saeedsg220** [comment] 2024-11-30 20:43
![Farming Simulator 25 Screenshot 2024 12 01 - 00 11 42 71](https://github.com/user-attachments/assets/176d8248-b448-45ae-be9a-e6cee8f8048c)
I think the problem is with the pink square under the trailer.
Not the right place

**Comment by loki79uk** [comment] 2024-12-01 23:03
Please try deleting your mod settings file
e.g. `C:\Users\Loki\Documents\My Games\FarmingSimulator2025\modSettings\UniversalAutoload.xml`

and update to the latest release version.  I think it should all be working now.

**Comment by Trivium1709** [comment] 2024-12-01 23:08
> Please try deleting your mod settings file e.g. `C:\Users\Loki\Documents\My Games\FarmingSimulator2025\modSettings\UniversalAutoload.xml`
> 
> and update to the latest release version. I think it should all be working now.

Works pretty well atm, good job!

**Comment by loki79uk** [comment] 2024-12-01 23:10
Great!  Closing as fixed (just to make it look like I have less work to do now) :D

**Closed by loki79uk** 2024-12-01 23:10 UTC
