### ISSUE TITLE
Farmtech DPW 1800

### ISSUE THREAD

**Issue by ahulleman** [loki79uk/FS25_UniversalAutoload#44] opened 2024-12-01 15:51 UTC
![Screenshot 2024-12-01 154459](https://github.com/user-attachments/assets/9364753d-0941-4376-a992-787d9b02ed4d)

Im trying to load Lettuce pallets on my trailer... When I first bought the trailer, it all loaded perfectly. But after I sold it at the farmers market , and tried to load my next load, The "loading box" seem to be moved to the trailer hitch area instead of the bed.
Not sure what causes this.
Attached screenshot.

**Comment by loki79uk** [comment] 2024-12-01 16:55
Do you still have the log from when this happened?

**Comment by ahulleman** [comment] 2024-12-01 16:59
I am a complete idiot when it comes to stuff like this... can you tell me where to find the logs? (and if they are in-game, how do i access them?)

**Comment by loki79uk** [comment] 2024-12-01 17:20
in the same folder as you savegames: C:\Users\Loki\Documents\My Games\FarmingSimulator2025\log.txt

**Comment by ahulleman** [comment] 2024-12-01 17:41
[log.txt](https://github.com/user-attachments/files/17969779/log.txt)
Attached.. Also had issues with the curtainsider not being able to load.
I ALT_F4'd a few minutes after so the relevant logs should be the latest lines?

**Comment by loki79uk** [comment] 2024-12-01 18:09
Thanks - I can't see anything that looks wrong which makes it harder to debug.  If you can find steps to reproduce it that would be great.  I'll try the same later, but the whole mod is currently broken for me at the moment because I'm making some changes to the order that the vehicles are configured.

**Comment by loki79uk** [comment] 2024-12-03 22:28
I have no idea about this one unless you edited the vehicle in the shop, or bought one in another game where you moved the loading zone forwards like that.  Does that sound possible?

**Comment by loki79uk** [comment] 2024-12-06 00:46
Closing as can't reproduce, but if you find a way to reproduce it then please re-open.

**Closed by loki79uk** 2024-12-06 00:46 UTC
