### ISSUE TITLE
Breaking Custom fences

### ISSUE THREAD

**Issue by nezman71** [loki79uk/FS25_UniversalAutoload#75] opened 2024-12-04 01:19 UTC
when the autoloader mod is installed, you cannot finish a custom fence on animal pens. the game allows you to draw it, but when selecting the last green pole, it does not transition to the finish phase.

**Comment by loki79uk** [comment] 2024-12-04 09:15
Can you please attach a log file from when this happened?

**Comment by geeknessfr** [comment] 2024-12-04 10:20
I just tested on my PC, with mod installed, and I can build custom fences around animal pens, do you have any other mod installed ?

![image](https://github.com/user-attachments/assets/c66c9c5f-3d02-426f-9669-77e6716b4b4c)

**Comment by loki79uk** [comment] 2024-12-06 00:56
Did you manage to reproduce this again?

**Comment by loki79uk** [comment] 2024-12-07 01:03
Closing as can't reproduce.

**Closed by loki79uk** 2024-12-07 01:03 UTC

**Comment by nezman71** [comment] 2024-12-07 03:08
I was just going to say close it. i was able to finish the fence by
clicking off away from the green fence pole, not directly on it.
thanks for looking into it.
