### ISSUE TITLE
Version 0.0.9 "Error: Unsupported mod description version in mod FS25_UniversalAutoload"

### ISSUE THREAD

**Issue by joridiculous** [loki79uk/FS25_UniversalAutoload#58] opened 2024-12-02 14:34 UTC
Really weird one. Guess FS dont like  0.0.0.9 .. 
(Release version of game btw)

**Comment by joridiculous** [comment] 2024-12-02 14:51
Ok i dont get this one at all. I tried to change the version to all kind of different ones but they all end up with same error:
Available mod: (Hash: 2ef26c1f7feec941230a8fec72888982) (Version: 1.0.0.9) FS25_UniversalAutoload
Error: Unsupported mod description version in mod FS25_UniversalAutoload

**Comment by xpedicion** [comment] 2024-12-02 14:53
You should update your FS, then. They bumped the descVersion from 92 to 93 for the current FS version.

**Comment by joridiculous** [comment] 2024-12-02 15:01
Just figured that one out. Changed <modDesc descVersion="93"> too 92 and mod loads. 
And i will not go back on 1.3X until the reverts the steering. It is unplayable on controller

Guess this one can be closed as kind of solved, unless there is some other incompatibility :)

**Comment by geeknessfr** [comment] 2024-12-02 16:06
You can close the issue yourself. Also, the error is caused by YOU not updating your game, so it’s not related to the mod...

**Closed** 2024-12-02 17:11 UTC
