### ISSUE TITLE
Unable to load more logs

### ISSUE THREAD

**Issue by cwhandersen** [loki79uk/FS25_UniversalAutoload#123] opened 2024-12-12 16:36 UTC
Loving the progress on the log loading.
Am I doing something wrong with this? I can load logs, but it only loads some logs and then stops. 
When I press start loading again it says "Unable to load any more items of this size."
Picture attached:

https://imgur.com/a/mO33gMF

**Comment by loki79uk** [comment] 2024-12-12 16:49
How big is the loading volume set?  Try making it taller and it should take more logs.

**Comment by cwhandersen** [comment] 2024-12-12 17:06
My truck is leased. So can't show you.
But made the loading area like this.

https://imgur.com/a/VaUrDLl

**Comment by cwhandersen** [comment] 2024-12-12 17:20
Tried this trailer instead.
And it works exactly as expected.
Might have made the box wrong on the yellow truck then.

https://imgur.com/a/zr65brl

**Comment by loki79uk** [comment] 2024-12-12 21:59
Okay, glad you got it working.  Closing as can't reproduce.

**Closed by loki79uk** 2024-12-12 21:59 UTC

**Comment by porshkevich** [comment] 2024-12-21 16:00
Sorry, but the problem still exists, and it is clearly not related to the length of the logs. If you load logs under a contract, there are sometimes 15+ of them loaded into THIS transport, but when we cut dead wood, there is no way to fill the entire truck.

![изображение](https://github.com/user-attachments/assets/392ce415-f045-41b7-abe8-120f163ee3d6)

If necessary, I can open a new issue and provide more necessary screenshots/logs.

**Comment by loki79uk** [comment] 2024-12-21 16:07
Is this set as a log trailer - can you attach your log file and the mod settings file.

**Comment by porshkevich** [comment] 2024-12-21 16:51
[log+settings.zip](https://github.com/user-attachments/files/18219305/log%2Bsettings.zip)

Fresh log and settings

**Comment by porshkevich** [comment] 2024-12-21 16:54
![изображение](https://github.com/user-attachments/assets/cee6b3b6-f423-4f30-b575-e5aa5d4e5b74)

Current state sceenshot. some logs autoloaded, but if try add new - cannot

**Comment by loki79uk** [comment] 2024-12-21 17:59
You have not set it as a log trailer.  Maybe you bought it before that was possible, but you can either edit the file or set it in the shop and buy again.

you have:
```xml
        <vehicle configFileName="data/vehicles/riedler/timberFrameFH16/timberFrameFH16.xml">
            <configuration selectedConfigs="1">
                <loadingArea offset="0.009 1.531 -1.112" width="2.548496" length="5.918465" height="2.818029"/>
            </configuration>
        </vehicle>
```

should be:
```xml
        <vehicle configFileName="data/vehicles/riedler/timberFrameFH16/timberFrameFH16.xml">
            <configuration selectedConfigs="1">
                <options isLogTrailer="true"/>
                <loadingArea offset="0.009 1.531 -1.112" width="2.548496" length="5.918465" height="2.818029"/>
            </configuration>
        </vehicle>
```

**Comment by porshkevich** [comment] 2024-12-21 18:55
Awesome! I didn't think that the default trailer would have problems with auto-detection of settings (and I reset settings file  as recommended in v.0.2.0.0) 

`isLogTrailer` is really help. This is even noticeable by the way the model/method of loading the logs has changed(Not an attempt to construct vertical points, but a distribution over the occupied space in a thin layer).

**Comment by loki79uk** [comment] 2024-12-21 20:05
Yes, basically without the isLogTrailer it just treats the logs like square pallets and tries to stakc them.  It is fine for small logs that you cut by hand for selling onto small trailers or pickups, but for proper logging you need the log trailer flag set.  This means you then cannot load other things (like pallets or bales).
