### ISSUE TITLE
MERLOT UNLOAD

### ISSUE THREAD

**Issue by Rayman025** [loki79uk/FS25_UniversalAutoload#100] opened 2024-12-07 22:44 UTC
Hey,

We can't unload from the merlot. Only with tractor/truck.

Bye

**Comment by loki79uk** [comment] 2024-12-07 22:56
Can you please make sure your are using the latest version (v0.0.0.17) and then if still not working attach your log file to this bug.

**Comment by loki79uk** [comment] 2024-12-08 14:29
Closing as duplicate of https://github.com/loki79uk/FS25_UniversalAutoload/issues/94

**Closed by loki79uk** 2024-12-08 14:29 UTC
