### ISSUE TITLE
Bale loading v0.3.0 dedicated server

### ISSUE THREAD

**Issue by Cleef28** [loki79uk/FS25_UniversalAutoload#175] opened 2024-12-21 07:37 UTC
Hi 
we updated to v0.3.0 yesterday and it seems that the loading of bales does not work properly. 

In layer mode the first layer use loaded correctly but after that the second layer is loaded into the first layer. 
The third layer is loaded on top of the first layer again.
With round bales this leads to bales flying everywhere. While with quarter bales they usually move them self into correct position.

In stacking mode here I only tested it with round bales. But when the trailer was full visually the bales also where moved into each other instead of stopping loading. 

I don't know if this is a configuration issue on our side. I can look for logs once I'm home today and will attach them.

**Comment by Cleef28** [comment] 2024-12-21 09:38
```
2024-12-21 10:33 *** UNIVERSAL AUTOLOAD - FOUND NEW OBJECT TYPE: data/objects/bales/roundbales/roundbale180/roundbale180.i3d ***
2024-12-21 10:33 Round Bale
2024-12-21 10:33   width: 1.2
2024-12-21 10:33   height: 1.8
2024-12-21 10:33   length: 1.8
2024-12-21 10:33   size X: 1.8172607421875
2024-12-21 10:33   size Y: 1.816802978515625
2024-12-21 10:33   size Z: 1.1423110961914062
2024-12-21 10:33   offset X: 0.00018310546875
2024-12-21 10:33   offset Y: -0.000091552734375
2024-12-21 10:33   offset Z: 0.001033782958984375
2024-12-21 10:33 Round Bale flipYZ
2024-12-21 10:33   >> data/objects/bales/roundbales/roundbale180/roundbale180.i3d [1.817, 1.142, 1.817] - BALE
2024-12-21 10:33 STOP LOADING (items loaded = 16)
2024-12-21 10:33 STOP LOADING (items loaded = 17)
2024-12-21 10:33 STOP LOADING (items loaded = 18)
2024-12-21 10:33 Game saved successfully.
2024-12-21 10:33 206250 FULLY UNLOADED - RESET LOADING AREA
2024-12-21 10:34 206250 FULLY UNLOADED - RESET LOADING AREA

2024-12-21 10:34 STOP LOADING (items loaded = 19)

2024-12-21 10:34 STOP LOADING (items loaded = 20)

2024-12-21 10:34 STOP LOADING (items loaded = 22)

2024-12-21 10:35 STOP LOADING (items loaded = 23)

2024-12-21 10:35 STOP LOADING (items loaded = 24)

2024-12-21 10:35 STOP LOADING (items loaded = 25)


```
Config of the trailer: 
![Screenshot 2024-12-21 103757](https://github.com/user-attachments/assets/734745cf-a7a6-4862-ab1f-d2a6fd00a563)

**Comment by loki79uk** [comment] 2024-12-21 09:39
Is this with all trailers, or one specific trailer?  Please attach a log file and also check there are not two overlapping loading zones defined for that trailer.

**Comment by loki79uk** [comment] 2024-12-21 10:00
So there was a game save in the middle of loading?

**Comment by Cleef28** [comment] 2024-12-21 11:04
Could be but i had it all the time and not only this once. 

I least a new trailer and restarted the server but the autoload wasnt working anymore on all trailers. 
Also the server wouldnt start anymore afterwards. 
Maybe there was an issue with the config? I deleted it and afterwards the server started again. 
[UniversalAutoload.txt](https://github.com/user-attachments/files/18218228/UniversalAutoload.txt)

Also i updated to v0.3.2 and now it seems to work again. 

[log_2024-12-21_11-30-18.txt](https://github.com/user-attachments/files/18218230/log_2024-12-21_11-30-18.txt)

**Comment by loki79uk** [comment] 2024-12-21 11:16
> Could be but i had it all the time and not only this once.
> 
> I least a new trailer and restarted the server but the autoload wasnt working anymore on all trailers. Also the server wouldnt start anymore afterwards. Maybe there was an issue with the config? I deleted it and afterwards the server started again. [UniversalAutoload.txt](https://github.com/user-attachments/files/18218228/UniversalAutoload.txt)
> 
> Also i updated to v0.3.2 and now it seems to work again.
> 
> [log_2024-12-21_11-30-18.txt](https://github.com/user-attachments/files/18218230/log_2024-12-21_11-30-18.txt)

So yes 3.0.0.0 has the bug with sending new configs on the server, BUT something else has gone wrong because you have 34 loading zones defined!!
```
2024-12-21 11:35 CONFIG RECIEVED ON SERVER:
2024-12-21 11:35 --horizontalLoading :: true
2024-12-21 11:35 --loadArea :: table: 0x00000211f21d3658
2024-12-21 11:35 --    1 :: table: 0x00000211f21d3628
2024-12-21 11:35 --        baleHeight :: -8.125647202349758e-15
2024-12-21 11:35 --        reverseLengthAxis :: false
2024-12-21 11:35 --    2 :: table: 0x00000211f21d3478
2024-12-21 11:35 --        offset :: table: 0x00000211f21d3418
2024-12-21 11:35 --    3 :: table: 0x00000211f21d2ea8
2024-12-21 11:35 --    4 :: table: 0x00000211f21d1d08
2024-12-21 11:35 --    5 :: table: 0x00000211f21d1258
2024-12-21 11:35 --    6 :: table: 0x00000211f21d07a8
2024-12-21 11:35 --    7 :: table: 0x00000211f21c7ce8
2024-12-21 11:35 --    8 :: table: 0x00000211f21c75c8
2024-12-21 11:35 --    9 :: table: 0x00000211f21c6758
2024-12-21 11:35 --    10 :: table: 0x00000211f21c5618
2024-12-21 11:35 --    11 :: table: 0x00000211f21c48c8
2024-12-21 11:35 --    12 :: table: 0x00000211f21e6fb8
2024-12-21 11:35 --    13 :: table: 0x00000211f21e5ed8
2024-12-21 11:35 --    14 :: table: 0x00000211f21e49a8
2024-12-21 11:35 --    15 :: table: 0x00000211f21ef398
2024-12-21 11:35 --    16 :: table: 0x00000211f21ee918
2024-12-21 11:35 --    17 :: table: 0x00000211f21ecf68
2024-12-21 11:35 --    18 :: table: 0x00000211f21f1248
2024-12-21 11:35 --    19 :: table: 0x00000211f21f7e98
2024-12-21 11:35 --    20 :: table: 0x00000211f21f7898
2024-12-21 11:35 --    21 :: table: 0x00000211f21f7358
2024-12-21 11:35 --    22 :: table: 0x00000211f21f6cf8
2024-12-21 11:35 --    23 :: table: 0x00000211f21f6bd8
2024-12-21 11:35 --    24 :: table: 0x00000211f21f6158
2024-12-21 11:35 --    25 :: table: 0x00000211f21f6038
2024-12-21 11:35 --    26 :: table: 0x00000211f21f5b28
2024-12-21 11:35 --    27 :: table: 0x00000211f21f4238
2024-12-21 11:35 --    28 :: table: 0x00000211f2263388
2024-12-21 11:35 --    29 :: table: 0x00000211f2272dc8
2024-12-21 11:35 --    30 :: table: 0x00000211f2272558
2024-12-21 11:35 --    31 :: table: 0x00000211f2271f88
2024-12-21 11:35 --    32 :: table: 0x00000211f2271bf8
2024-12-21 11:35 --    33 :: table: 0x00000211f2271388
2024-12-21 11:35 --    34 :: table: 0x00000211f2270f68
```

**Comment by Cleef28** [comment] 2024-12-21 11:21
Yes I saw that in the config but I'm not sure how it happend.

I changed the trailer once after updating to v0.3.0 to change it to the bale Trailer

**Comment by loki79uk** [comment] 2024-12-21 11:23
> Yes I saw that in the config but I'm not sure how it happend.
> 
> I changed the trailer once after updating to v0.3.0 to change it to the bale Trailer

It could certainly be a bug related to the one in https://github.com/loki79uk/FS25_UniversalAutoload/issues/173

If it works now in 0.3.0.2 then I guess that was it, but if it happens again please keep the log file if you can

**Comment by loki79uk** [comment] 2024-12-21 12:43
My best guess is related to bug #173 the network transfer got out of sync, so it somehow ended up reading the wrong number of zones and then created a load of new ones:
```lua
	print("loadingAreas:")
	config.loadArea = {}
	nAreas = streamReadInt8(streamId) or 0
	for j=1, nAreas do
		config.loadArea[j] = {}
		local loadAreaKey = string.format(".loadingArea(%d)", j-1)
		iterateDefaultsTable(UniversalAutoload.LOADING_AREA_DEFAULTS, configKey, loadAreaKey, config.loadArea[j], recieveValues)
	end
```

**Comment by loki79uk** [comment] 2024-12-21 19:08
Closing as a duplicate of #173, but if you ever get the many zones bug, then please let me know the steps to reproduce it!

**Closed by loki79uk** 2024-12-21 19:08 UTC
