### ISSUE TITLE
Error when using save on another PC

### ISSUE THREAD

**Issue by User-47186985** [loki79uk/FS25_UniversalAutoload#98] opened 2024-12-07 17:33 UTC
Hello, 
I synced my save to another PC via Steam, and now the trailer shows *LOAD AREAS MISSING*. I have bought a new trailer and that one works perfectly. But the old ons still shows the error. Is there any way to fix this or do I need to get rid of the old trailer?

**Comment by loki79uk** [comment] 2024-12-07 17:38
You need to transfer the settings file from your mod settings folder:
C:\Users\Loki\Documents\My Games\FarmingSimulator2025\modSettings\UniversalAutoload.xml

In later versions this will be populated with defaults, but for now to make debugging easier it is only those you have configured yourself.  The other way is to make a new savegame, buy all the same trailers, then close that and start your imported game.  But copying the file is faster!

**Comment by loki79uk** [comment] 2024-12-07 20:34
A wider question related to this bug is do we want to save all settings PER VEHICLE?  Then they could go into the savegame, but then the issue is what happens if you want to change the settings for all vehicles.  It could get very confusing if you are used to a global setting for each trailer type.

**Comment by loki79uk** [comment] 2024-12-11 19:29
Closing as duplicate of https://github.com/loki79uk/FS25_UniversalAutoload/issues/69

**Closed by loki79uk** 2024-12-11 19:29 UTC
