### ISSUE TITLE
Unable to Load any more items of this size

### ISSUE THREAD

**Issue by Dalaquin** [loki79uk/FS25_UniversalAutoload#81] opened 2024-12-05 00:25 UTC
hey sorry if this has been covered, Updated to latest release. Anything i buy in store works great. The first time. Unload and return to autoload some more and it gives an error "Unable to load any more items of this size". then it straps down the empty trailer and that's it.  Sell vehicle and buy a new one works great one time, then rinse and repeat. Was working fine on I think .9 but then today thats happening.

**Comment by loki79uk** [comment] 2024-12-05 00:32
> hey sorry if this has been covered, Updated to latest release. Anything i buy in store works great. The first time. Unload and return to autoload some more and it gives an error "Unable to load any more items of this size". then it straps down the empty trailer and that's it.  Sell vehicle and buy a new one works great one time, then rinse and repeat. Was working fine on I think .9 but then today thats happening.

Sorry about that, I thought I had tested enough things that were all working 😕 

Can you attach your log file.  I won't be able to look until tomorrow now.

**Comment by Dalaquin** [comment] 2024-12-05 01:57
[log.txt](https://github.com/user-attachments/files/18016244/log.txt)

**Comment by loki79uk** [comment] 2024-12-05 08:34
Thank you that is helpful.

I see we get: `2024-12-04 18:55 FULL - NO MORE ROOM`
But then the loading area is never reset.

What did you do to unload?  did you just drive over the sellpoint, or actually press unload?

I think it must be the same as https://github.com/loki79uk/FS25_UniversalAutoload/issues/82 where the sellpoint is taking the pallets, but the trigger does not activate the callback as it should.  I will set up a savegame to reproduce this and update here when fixed.

**Comment by Dalaquin** [comment] 2024-12-05 12:10
Yeah just drove over the sellpoint, just hitting L to remove the straps.

**Comment by loki79uk** [comment] 2024-12-05 12:17
> Yeah just drove over the sellpoint, just hitting L to remove the straps.

Trying to reproduce but can't.  Does it happen for you every single time?  Can you think of anything else?
- You said it only works when you buy them, is it the same if you save and reload the game?
- Did you unload any items by hand (with strength) or if some fell off while driving, etc?
- Which actual sell point are you using?  Don't think it should matter, but worth a try.

If you can zip a savegame where it is about to happen (e.g. loaded trailer near sell point), then I can try to reproduce with that.

**Comment by loki79uk** [comment] 2024-12-05 16:44
The number in that debugging string is `# loaded / available`

So if it ever won't load but it is actually empty - I suspect it would say a number greater than 0 for loaded. But I still don't know HOW that could happen..

**Comment by bgauger** [comment] 2024-12-05 23:38
[log.txt](https://github.com/user-attachments/files/18030925/log.txt)
Similar issue is happening to me. drove over the sell point.

**Comment by loki79uk** [comment] 2024-12-06 00:02
> [log.txt](https://github.com/user-attachments/files/18030925/log.txt) Similar issue is happening to me. drove over the sell point.

Was it at the end where you drove over the sell point? with the woodBeamPallet?

Did you happen to notice what the numbers were on the bottom of the F1 menu? https://github.com/loki79uk/FS25_UniversalAutoload/issues/81#issuecomment-2520184568   I think I need to add more debugging stuff to really see what is going on here..

**Comment by loki79uk** [comment] 2024-12-11 19:21
I think this is a duplicate of bug #108 - so if correct then the issue only happened if you went fast enough when driving to the sell point.  Hopefully fixed now in latest versions.  https://github.com/loki79uk/FS25_UniversalAutoload/releases

_I think it could still happen if you have the straps unstrapped, and manage to go fast enough without the load falling off anyway.._

**Closed** 2024-12-11 19:22 UTC

**Comment by toruonu** [comment] 2025-03-05 12:14
Still there. I may have driven through too fast as well (didn't know it could cause issues) and now even if I buy a new trailer (even a different brand) I cannot load anything to it.

![Image](https://github.com/user-attachments/assets/abd2835c-4222-4e21-86f3-c2cb31cb85dd)
![Image](https://github.com/user-attachments/assets/9ce5554c-03e9-4ae4-bf80-0c6d2a4e6e91)

[log.txt](https://github.com/user-attachments/files/19088802/log.txt)

**Comment by loki79uk** [comment] 2025-03-05 12:37
> Still there. I may have driven through too fast as well (didn't know it could cause issues) and now even if I buy a new trailer (even a different brand) I cannot load anything to it.
> 
> ![Image](https://github.com/user-attachments/assets/abd2835c-4222-4e21-86f3-c2cb31cb85dd)
> ![Image](https://github.com/user-attachments/assets/9ce5554c-03e9-4ae4-bf80-0c6d2a4e6e91)
> 
> [log.txt](https://github.com/user-attachments/files/19088802/log.txt)

Can you try with the latest version please?  That makes no sense if it is happening with brand new different trailers.  Try deleting/renaming your mod settings file so that everything is using defaults again.

**Comment by toruonu** [comment] 2025-03-05 14:11
I am using the latest version (just verified by downloading it again). Also I removed the modSettings/UniversalAutoload.xml file (it was recreated), went to another savegame, bought the trailer, logged out of the savegame and back to my one with issues and voila, it still can't load... so it looks like it's something that's gotten stuck in the savegame or I can't really figure out what it could be. I did sell about 150 pallets of lettuce just before by loading them on the trailer and taking them to the farm shop. Then I went to get the lettuce from storage (Anywhere Object Storage mod). Those pallets didn't want to get loaded and from there it started... 

So I went back to the savegame and took the trailer to a freshly spawned pallet of Lettuce and it happily loaded those. It looks to me that there is some kind of weird interference with the universal storage. Once a pallet came out it refused to go on the trailer due to objects of this size not fitting. Any ideas how to further debug this?

**Comment by toruonu** [comment] 2025-03-05 14:14
Indeed, when I turned off the anywhere object storage mod the pallets became loadable. So there seems to be those two mods conflicting with each other. Now I have to see if I can somehow get the pallets out of all the storage and if I can then transport them, but will need to figure out why those two interfere.
