### ISSUE TITLE
Loading Bug

### ISSUE THREAD

**Issue by bulllox** [loki79uk/FS25_UniversalAutoload#104] opened 2024-12-08 19:53 UTC
First sorry for my English 

The pallets loading is weried 

![pallets](https://github.com/user-attachments/assets/43fe028d-0f0b-4138-9058-5646724e4b17)

As you can see thats not how it should be loaded

**Comment by loki79uk** [comment] 2024-12-08 20:19
I think this is probably related to these changes from https://github.com/loki79uk/FS25_UniversalAutoload/issues/43

Were those pallets all loaded in one go?  Can you please unload and reload and then send me the log file?

**Comment by loki79uk** [comment] 2024-12-11 19:31
Is this still happening?  I need more information to tell if this is a bug or if you just loaded a few items at a time.

**Comment by loki79uk** [comment] 2024-12-13 22:43
I think I've found the cause of this.  It happens when pallets are similar size but not identical.  Will work on a fix now.

**Comment by bulllox** [comment] 2024-12-13 23:03
Sry for late reply wasn't home, well unloading and reloading sometimes leads to it loading it differently but still wrong. But since you found it thats great

**Comment by loki79uk** [comment] 2024-12-13 23:39
I made a workaround.  I just added a small delta (0.005) for the size comparisons.

without:
![image](https://github.com/user-attachments/assets/009203ca-25fe-46e7-8c8a-16405a225cef)

with:
![image](https://github.com/user-attachments/assets/50a36c18-d8cd-4366-9231-89612910f3cf)

**Comment by loki79uk** [comment] 2024-12-14 00:06
Should be fixed now - if not I can increase the delta (until the pallets start clipping!)
https://github.com/loki79uk/FS25_UniversalAutoload/releases

**Closed** 2024-12-16 13:17 UTC
