### ISSUE TITLE
F1 informations  V0.0.1.0

### ISSUE THREAD

**Issue by morpheus0815** [loki79uk/FS25_UniversalAutoload#63] opened 2024-12-03 14:21 UTC
Dear Team, 
this might be prio LOW but just to inform you. 
by version 0.0.0.1.0 the texts 

"430636 *** LOAD AREAS MISSING *** "
"430747 *** LOAD AREAS MISSING *** "

Is shown directly by the start of a new game.
<img width="488" alt="image" src="https://github.com/user-attachments/assets/4163de9d-a0bd-4786-86cb-41b0826c0bb8">

**Comment by loki79uk** [comment] 2024-12-03 14:31
If you read the release notes, this is a notice for you to look at your mod settings file.  It should have some entries with missing load areas

Something like:
![391676269-ec2c59e7-7e8b-4f01-a856-98951bc9902d](https://github.com/user-attachments/assets/d7faa18d-ceed-4cd2-ae78-ab2b216d2ce3)

If you have any entries like that then either delete them, or probably easier to just delete the whole file.

**Comment by loki79uk** [comment] 2024-12-03 14:36
I think it will also show up until you add the settings again - take those vehicles to the shop to configure them, or buy another one of the same type.

**Comment by aurelien2023** [comment] 2024-12-03 14:37
I have the same issue 
![20241203153412_1](https://github.com/user-attachments/assets/3246455f-2ae5-4240-a15d-dfd667f181f2)
but nothing un the mod settings : 
![image](https://github.com/user-attachments/assets/853dea28-7aad-4e61-bed5-7cffbf62af4e)

**Comment by aurelien2023** [comment] 2024-12-03 14:38
and can't figure out wich vehicule are showing the error...

**Comment by aurelien2023** [comment] 2024-12-03 14:42
[Modsettings-UniversalAutoload.zip](https://github.com/user-attachments/files/17994636/Modsettings-UniversalAutoload.zip)

**Comment by loki79uk** [comment] 2024-12-03 14:46
Maybe it is a false positive, it could even be the train or something like that..  Don't worry about it for now - it is just a warning because a lot of people do have this issue.

**Comment by aurelien2023** [comment] 2024-12-03 14:48
ok can you print the UAL code in the mod setting to help in research ?

**Comment by aurelien2023** [comment] 2024-12-03 14:59
![20241203155725_1](https://github.com/user-attachments/assets/1be800ff-55fe-43df-a8cf-05fc5894a06e)
and the UAL code change at every new reload of the save game

**Comment by geeknessfr** [comment] 2024-12-03 15:07
I get this messages too **without any UAL settings xml** and just with a **freshly new game** :
![image](https://github.com/user-attachments/assets/d3824ff4-b2f4-4e7c-a795-dde73dabea54)

**Comment by geeknessfr** [comment] 2024-12-03 15:37
For those who want to hide the messages while loki79 fixes this "train issue"... you can add the following lines to the file in modSettings:

**NOTE :
It's just a temporarly workaround, the size of the loading area is not accurate at all ^^
And you'd have to remove those lines when the fix will be released.**

```
        <vehicle configFileName="data/vehicles/train/wagonFlatBedUS/wagonFlatBedUS.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.001 1.094 -0.123" width="2.447945" length="10.0" height="2.460419"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/train/wagonTimberUS/wagonTimberUS.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.001 1.094 -0.123" width="2.447945" length="10.0" height="2.460419"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/train/wagonTimberEU/wagonTimberEU.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.001 1.094 -0.123" width="2.447945" length="10.0" height="2.460419"/>
            </configuration>
        </vehicle>
```

The complete file should be like this if you didn't have any other vehicle : 

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="data/vehicles/train/wagonFlatBedUS/wagonFlatBedUS.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.001 1.094 -0.123" width="2.447945" length="10.0" height="2.460419"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/train/wagonTimberUS/wagonTimberUS.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.001 1.094 -0.123" width="2.447945" length="10.0" height="2.460419"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/train/wagonTimberEU/wagonTimberEU.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.001 1.094 -0.123" width="2.447945" length="10.0" height="2.460419"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
</universalAutoload>

```

**Comment by Kolnerke** [comment] 2024-12-03 16:04
Where can I find the modsettings? I have the mod installed but I have also the "Load Area Missing"

**Comment by geeknessfr** [comment] 2024-12-03 16:11
> Where can I find the modsettings? I have the mod installed but I have also the "Load Area Missing"
> 
> Mod isn't working either, it gives me the commands but it doesn't work.
> 
> I bought the trailer, giving me the autoload.

You can find the file `UniversalAutoloader.xml` file in `Documents\My Games\FarmingSimulator2025\modSettings`

**Comment by Kolnerke** [comment] 2024-12-03 16:27
That's what I thought, but the file is not in the folder. 
I have the realtimeclock mod and the lumberjack mod, they are in the modsettingfolder.

**Comment by PARADOX070** [comment] 2024-12-03 16:34
The XML file also seem to be missing for me. Here is part of the log

```
2024-12-03 17:23 SET HEIGHT
2024-12-03 17:23 SET HEIGHT
2024-12-03 17:23 INIT SHOP CONFIG
2024-12-03 17:24 DELETE SHOP VEHICLE: Brandt H550 Beavertail - UAL #810430
2024-12-03 17:24 Brandt H550 Beavertail: UAL - tension belts (8)
2024-12-03 17:24 UniversalAutoload - supported vehicle: Brandt H550 Beavertail - UAL #814046 #ALL (UNIQUE)
2024-12-03 17:24 *** NO LOCAL CONFIGS AVAILABLE - #ALL (UNIQUE) ***
2024-12-03 17:24 CREATE REAL VEHICLE: Brandt H550 Beavertail - UAL #814046
2024-12-03 17:24 WORKSHOP VEHICLE STILL EXISTS 810430
2024-12-03 17:24 CLONE SETTINGS FROM SHOP VEHICLE
2024-12-03 17:24 TO DO: import the rest of the parameters here...
2024-12-03 17:24 UAL - SAVE VEHICLE CONFIGURATION
2024-12-03 17:24 EXPORT VEHICLE SETTINGS: Brandt H550 Beavertail - UAL #814046
2024-12-03 17:24 Creating NEW settings file C:/Users/***/Documents/My Games/FarmingSimulator2025/modSettings/UniversalAutoload.xml
2024-12-03 17:24 FIND CORRECT SETTINGS FILE POSITION:
2024-12-03 17:24 configFileName = data/vehicles/brandt/h550/h550.xml
2024-12-03 17:24 selectedConfigs = ALL
2024-12-03 17:24 Error: Running LUA method 'update'.
C:/Users/***/Documents/My Games/FarmingSimulator2025/mods/FS25_UniversalAutoload/UniversalAutoloadInstaller.lua:475: attempt to index nil with 'ALL'
2024-12-03 17:24 UAL: ON POST LOAD - RESET
2024-12-03 17:24 INITIALISE UAL VEHICLE (ON UPDATE) 814046
2024-12-03 17:24 UAL - FATAL ERROR: Brandt H550 Beavertail - UAL #814046
2024-12-03 17:24 C:/Users/***/Documents/My Games/FarmingSimulator2025/mods/FS25_UniversalAutoload/UniversalAutoload.lua:1315: attempt to index nil with 'actualRootNode'
2024-12-03 17:24 [PowerTools] Warning: Failed to register main key for PowerTools
2024-12-03 17:24 CALLBACK actionEventToggleLoading: Brandt H550 Beavertail - UAL #814046
2024-12-03 17:24 CALLBACK actionEventToggleLoading: Brandt H550 Beavertail - UAL #814046
2024-12-03 17:24 CALLBACK actionEventToggleLoading: Brandt H550 Beavertail - UAL #814046
2024-12-03 17:24 CALLBACK actionEventToggleLoading: Brandt H550 Beavertail - UAL #814046
2024-12-03 17:24 CALLBACK actionEventToggleLoading: Brandt H550 Beavertail - UAL #814046
2024-12-03 17:24 CALLBACK actionEventUnloadAll: Brandt H550 Beavertail - UAL #814046
2024-12-03 17:24 CALLBACK actionEventUnloadAll: Brandt H550 Beavertail - UAL #814046
2024-12-03 17:24 CALLBACK actionEventToggleLoading: Brandt H550 Beavertail - UAL #814046
2024-12-03 17:24 CALLBACK actionEventToggleLoading: Brandt H550 Beavertail - UAL #814046
2024-12-03 17:24 CALLBACK actionEventToggleLoading: Brandt H550 Beavertail - UAL #814046
2024-12-03 17:25 UAL - ON VEHICLE BUY EVENT (owned)
2024-12-03 17:25 [PowerTools] Warning: Failed to register main key for PowerTools
2024-12-03 17:29 Game saved successfully.
2024-12-03 17:29 
Script error in delete: Unknown entity id 314900 for 'object' in method 'delete'.
```

**Comment by loki79uk** [comment] 2024-12-03 16:38
> The XML file also seem to be missing for me. Here is part of the log
> 

> 2024-12-03 17:24 FIND CORRECT SETTINGS FILE POSITION:
> 2024-12-03 17:24 configFileName = data/vehicles/brandt/h550/h550.xml
> 2024-12-03 17:24 selectedConfigs = ALL
> 2024-12-03 17:24 Error: Running LUA method 'update'.
> C:/Users/***/Documents/My Games/FarmingSimulator2025/mods/FS25_UniversalAutoload/UniversalAutoloadInstaller.lua:475: attempt to index nil with 'ALL'
> 2024-12-03 17:24 UAL: ON POST LOAD - RESET
> 2024-12-03 17:24 INITIALISE UAL VEHICLE (ON UPDATE) 814046
> 2024-12-03 17:24 UAL - FATAL ERROR: Brandt H550 Beavertail - UAL #814046
> 2024-12-03 17:24 C:/Users/***/Documents/My Games/FarmingSimulator2025/mods/FS25_UniversalAutoload/UniversalAutoload.lua:1315: attempt to index nil with 'actualRootNode'

Thanks! these could be the cause of the issue for all the people getting it.

**Comment by PARADOX070** [comment] 2024-12-03 16:44
> > The XML file also seem to be missing for me. Here is part of the log
> 
> > 2024-12-03 17:24 FIND CORRECT SETTINGS FILE POSITION:
> > 2024-12-03 17:24 configFileName = data/vehicles/brandt/h550/h550.xml
> > 2024-12-03 17:24 selectedConfigs = ALL
> > 2024-12-03 17:24 Error: Running LUA method 'update'.
> > C:/Users/_**/Documents/My Games/FarmingSimulator2025/mods/FS25_UniversalAutoload/UniversalAutoloadInstaller.lua:475: attempt to index nil with 'ALL'
> > 2024-12-03 17:24 UAL: ON POST LOAD - RESET
> > 2024-12-03 17:24 INITIALISE UAL VEHICLE (ON UPDATE) 814046
> > 2024-12-03 17:24 UAL - FATAL ERROR: Brandt H550 Beavertail - UAL #814046
> > 2024-12-03 17:24 C:/Users/**_/Documents/My Games/FarmingSimulator2025/mods/FS25_UniversalAutoload/UniversalAutoload.lua:1315: attempt to index nil with 'actualRootNode'
> 
> Thanks! these could be the cause of the issue for all the people getting it.

Just to add my mod after updating from 0.9 to 0.10 and deleting the XML file stopped working entirely because the new file isn't being created.

**Closed** 2024-12-03 17:03 UTC
