### ISSUE TITLE
Problem with version 0.2.2 Can't buy new equipment

### ISSUE THREAD

**Issue by Crowbarinspector** [loki79uk/FS25_UniversalAutoload#154] opened 2024-12-18 05:05 UTC
Good day.  
The problem I have is that after playing for a while. I noticed that when I want to buy new equipment, i can't
   I can  sell equipment as much as i want, but not buying new

Example: Lets say i want a new tractor.
Go to medium tractors category -> Can see all tractors, can't enter any specific tractors, for changing something/buying it. Enter key/mouse clicking does not work. Applies to everything. 
   For this to work again, i have to save -> exit -> and then start game again, i can now buy what i want, but then after a little while. Same thing happens, have to repeat save & exit & reloading. 

I checked the log, can't find anything that tells me what could be wrong. 
This happens every time you start the game, tried trying each mod individually. they work perfectly, 
Even tried some mods + Autoload v0.2.2, Then changed and then the mods i didn't try the first time. 
   Get the same buying problem there to
   
It's only when version 0.2.2 of autoload is active that the problem occurs. Tried with version 0.2.1.4 and then it works perfectly, even with all the other mods. Even tried with just Autoload 0.2.2 and no mods. Still got buying issue.

Are currently playing on map Monteith, Iowa. Have tried standard maps, and the same buying issue occurs if version 0.2.2 autoload is active.

**Comment by Crowbarinspector** [comment] 2024-12-18 05:56
Update. Noticed you hade released Autoload v0.2.2.1 after i wrote the issue i had before with 0.2.2.0. So i tried the NEW version. 
  And i haven't had any issues with buying new equipment, So far it works normally. Checked log file & it looks clean. 
Will write again if problem ocurse .

**Comment by loki79uk** [comment] 2024-12-18 08:43
Sounds like a duplicate of https://github.com/loki79uk/FS25_UniversalAutoload/issues/146

Did you download the first one from the same site?

**Comment by Crowbarinspector** [comment] 2024-12-18 09:24
Im not sure, i think i downloaded them from different sites.

**Comment by loki79uk** [comment] 2024-12-18 09:37
They all leech files from each other.  Best to get it from here, that is the one I uploaded.

**Closed** 2024-12-18 09:46 UTC
