### ISSUE TITLE
Log Loading issues

### ISSUE THREAD

**Issue by FrmrJon** [loki79uk/FS25_UniversalAutoload#113] opened 2024-12-11 08:35 UTC
Hi Loki, I'm loving Universal Autoload so far, especially the Log aspect. Unfortunately I keep having issues when trying to load logs, after unloading them. I Keep getting the red flashing message that says "Unable to load any more Items of this size. When I do shift F12 I see that there's an invisible log on the truck and the trailer that will not disappear. I'm not getting any errors or warnings in my log, it just will not let me load anything. It's doing this on a server as well as single player. 
![image](https://github.com/user-attachments/assets/a0f6b2a5-5634-4ef0-a38e-37697f42afd3)

**Comment by loki79uk** [comment] 2024-12-11 09:25
That isn't an invisible log, it is just the last place that something was attempted to be loaded.   I only just finished the first implementation of log loading at all last night, so I can guarantee there will be bugs.   I'll try your setup this evening, but if you can tell me the exact steps to reproduce I'll fix it this evening.  The outlines of the logs on the ground should be green (not grey), have you got any loading filters on?

**Comment by jufcar** [comment] 2024-12-11 09:37
I just encountered the same Problem, might have something to do with the wood transport contracts or the selling trigger. It worked fine the first time. After "unloading" the logs in the selling trigger of the mission directly from the trailer I tried to load the second batch and got the same message as OP. The ual mod may not register the direct selling from the trailer as removed logs.

**Comment by loki79uk** [comment] 2024-12-11 09:42
> I just encountered the same Problem, might have something to do with the wood transport contracts or the selling trigger. It worked fine the first time. After "unloading" the logs in the selling trigger of the mission directly from the trailer I tried to load the second batch and got the same message as OP. The ual mod may not register the direct selling from the trailer as removed logs.

That is certainly quite possible, I didn't do any testing apart from loading/unloading with the command keys.  In fs22 there was a check to see if the trailer was empty before loading, but GIANTS have broken the engine function that I was using for that, so I'll have to adjust it or think of an alternative..

**Comment by Roby1164** [comment] 2024-12-11 10:18
> > I just encountered the same Problem, might have something to do with the wood transport contracts or the selling trigger. It worked fine the first time. After "unloading" the logs in the selling trigger of the mission directly from the trailer I tried to load the second batch and got the same message as OP. The ual mod may not register the direct selling from the trailer as removed logs.
> 
> That is certainly quite possible, I didn't do any testing apart from loading/unloading with the command keys. In fs22 there was a check to see if the trailer was empty before loading, but GIANTS have broken the engine function that I was using for that, so I'll have to adjust it or think of an alternative..

I also encountered the problem, but I also understood that it is due to the length of the logs, if they are not all the same, even by just one centimeter, it does not load them, and returns that message, precisely because of the difference in length.
You should see if you can remove that constraint, at least for the wood.
Regarding the unloading, with the keyboard, unloaded in the positionable joinery, I had no problems.

**Comment by Roby1164** [comment] 2024-12-11 10:27
Another issue, but it is more of a suggestion, is that, better to sell and buy back the log trailer, and configure the loading area, so as to load the logs up to the maximum length of the trailer, see attached image.
![Screenshot_16](https://github.com/user-attachments/assets/2f6804f1-079c-473f-9277-99baa33e6f3e)

**Comment by geeknessfr** [comment] 2024-12-11 12:19
> I also encountered the problem, but I also understood that it is due to the length of the logs, if they are not all the same, even by just one centimeter, it does not load them, and returns that message, precisely because of the difference in length. You should see if you can remove that constraint, at least for the wood. Regarding the unloading, with the keyboard, unloaded in the positionable joinery, I had no problems.

Logs length is not a problem... I test the mod since yesterday and already tested with trees manually cutted with chainsaw and loaded with random tree sizes, like on this screenshots with 8m, 6m and 3m logs length...
![image](https://github.com/user-attachments/assets/8099191a-50d0-4c22-910b-2ed7a3695784)

For the initial issue of this post from @FrmrJon, I'm currently testing...

**Comment by geeknessfr** [comment] 2024-12-11 12:42
Found the bug... When you sell the logs **WITH** the betls fastened... this cause a bug in the mod...

After selling the logs, I can't reload the vehicle : 
![image](https://github.com/user-attachments/assets/5e5e4334-b21e-44ad-8c5c-a61c3da88292)

And in the log file : 
```
2024-12-11 13:29 START Loading: Riedler Fahrzeugbau FH16 780 - UAL #2184035 (0)
2024-12-11 13:29 STOP LOADING (items loaded = 9)

--------------------- Here I sold the logs, but no entry here...

--------------------- And then I try to unload the empty trailer ...
2024-12-11 13:36 UNLOAD ALL: Riedler Fahrzeugbau FH16 780 - UAL #2184035 (9) <-- the mod sees 9 logs loaded
```

**Comment by loki79uk** [comment] 2024-12-11 12:54
> Found the bug... When you sell the logs **WITH** the betls fastened... this cause a bug in the mod...

This is related to the fix for #108.  I didn't know you could sell with tension belts still on, but I guess that is only for pallets..

**Comment by onetaps** [comment] 2024-12-11 13:36
Okay here it is another scenario :) I'm testing this mod as well and here it is what i've found out. I'm aware it's not intended to use a sellpoints atm due to this what loki mentioned before. Regardless I've tried to play around anyway.

P.S. I hope that i've not missed any communication related with that problem but if thats something obvious/known you already are aware of then sorry for spam :)

Problem: UAL area loads dissapear after 2nd vehicle reset attempt

So here are the steps to reproduce:
1. Buy and configured a log trailer. 
2. Park the vehicle next to the logs (for testing purpose 6m logs been used), do not use any options
3. Fully load trailer
4. Drive on the sellpoint and unfasten all tension belts
5. "Sell" all logs
6. Drive next to the new wooden logs again (not possible to load any more of these/only few can be loaded)
7. Unfasten belts and deattach trailer from a truck
8. Reset the trailer to the store
9. ------- AFTER 1st Reset it works. Trailer can be used again. Could be a workaround for some people. --------

```
2024-12-11 13:44 Game saved successfully.
2024-12-11 13:44 PITTS Trailers LT40-8L: UAL - tension belts (4)
2024-12-11 13:44 IDENTIFIED LOG TRAILER
2024-12-11 13:44 UniversalAutoload - supported vehicle: PITTS Trailers LT40-8L - UAL #1471702 #ALL (UNIQUE)
2024-12-11 13:44 *** LOAD AREA MISSING FROM CONFIG - please check mod settings file ***
2024-12-11 13:44 *** NO MATCHING LOCAL CONFIG - #ALL (UNIQUE) ***
2024-12-11 13:44 CREATE REAL VEHICLE: PITTS Trailers LT40-8L - UAL #1471702
2024-12-11 13:44 WORKSHOP VEHICLE STILL EXISTS 630966
2024-12-11 13:44 CLONE SETTINGS FROM SHOP VEHICLE
2024-12-11 13:44 TO DO: import the rest of the parameters here...
2024-12-11 13:44 UAL - SAVE VEHICLE CONFIGURATION
2024-12-11 13:44 EXPORT VEHICLE SETTINGS: PITTS Trailers LT40-8L - UAL #1471702
2024-12-11 13:44 FIND CORRECT SETTINGS FILE POSITION:
2024-12-11 13:44 useConfigName = nil
2024-12-11 13:44 selectedConfig = ALL
2024-12-11 13:44 SAVE TO SETTINGS FILE
2024-12-11 13:44 targetConfigId: ALL
2024-12-11 13:44 selectedConfigs: ALL
2024-12-11 13:44 FOUND 'ALL' CONFIG AT #1
2024-12-11 13:44 UPDATE CONFIG #1 == ALL (#1)
2024-12-11 13:44 options:
2024-12-11 13:44   >> .options#isLogTrailer = true - false
2024-12-11 13:44 loadingAreas:
2024-12-11 13:44   >> .loadingArea(0)#offset = table: 0x00000215b44457b8 - 0 0 0
2024-12-11 13:44   >> .loadingArea(0)#width = 2.221805311060204 - 0
2024-12-11 13:44   >> .loadingArea(0)#length = 13.152103441610187 - 0
2024-12-11 13:44   >> .loadingArea(0)#height = 2.4640085148250677 - 0
2024-12-11 13:44 PITTS Trailers LT40-8L - UAL #1471702: UAL ACTIVATED
2024-12-11 13:44 INITIALISE UAL VEHICLE (ON LOAD) 1471702
2024-12-11 13:44 INITIALISE UAL VEHICLE (ON LOAD 2) 1471702
2024-12-11 13:44 UAL: ON POST LOAD - RESET
2024-12-11 13:44 UAL: ON POST LOAD COMPLETE
```

10. Fully load and repeat all steps 4-8
11. This time the "Area loads" should dissapear

```
2024-12-11 13:56 PITTS Trailers LT40-8L: UAL - tension belts (4)
2024-12-11 13:56 IDENTIFIED LOG TRAILER
2024-12-11 13:56 UniversalAutoload - supported vehicle: PITTS Trailers LT40-8L - UAL #2116383 #ALL (UNIQUE)
2024-12-11 13:56 *** LOAD AREA MISSING FROM CONFIG - please check mod settings file ***
2024-12-11 13:56 *** NO MATCHING LOCAL CONFIG - #ALL (UNIQUE) ***
2024-12-11 13:56 CREATE REAL VEHICLE: PITTS Trailers LT40-8L - UAL #2116383
2024-12-11 13:56 PITTS Trailers LT40-8L - UAL #2116383: UAL SETTINGS WERE NOT ADDED
2024-12-11 13:56 INITIALISE UAL VEHICLE (ON LOAD) 2116383
2024-12-11 13:56 WARNING: load area missing - check settings file
2024-12-11 13:56 UAL: ON POST LOAD - RESET
2024-12-11 13:56 UAL: ON POST LOAD COMPLETE
2024-12-11 13:57 PITTS Trailers LT40-8L: UAL - tension belts (4)
2024-12-11 13:57 IDENTIFIED LOG TRAILER
2024-12-11 13:57 UniversalAutoload - supported vehicle: PITTS Trailers LT40-8L - UAL #2169628 #ALL (UNIQUE)
2024-12-11 13:57 *** LOAD AREA MISSING FROM CONFIG - please check mod settings file ***
2024-12-11 13:57 *** NO MATCHING LOCAL CONFIG - #ALL (UNIQUE) ***
2024-12-11 13:57 CREATE REAL VEHICLE: PITTS Trailers LT40-8L - UAL #2169628
2024-12-11 13:57 PITTS Trailers LT40-8L - UAL #2169628: UAL SETTINGS WERE NOT ADDED
2024-12-11 13:57 INITIALISE UAL VEHICLE (ON LOAD) 2169628
2024-12-11 13:57 WARNING: load area missing - check settings file
2024-12-11 13:57 UAL: ON POST LOAD - RESET
2024-12-11 13:57 UAL: ON POST LOAD COMPLETE
```


Expected behaviour:
It is possible to use sellpoints with that config (i guess thats coming), but for now in the worst case scenario reset should fix the "problem" each time vehicle is beeing reset into the store. 
As it seems "vehicle reset" somehow fixes the problem (not fully but still). Maybe it would be possible to extract and somehow use the specific function out of the "reset feature" to trigger the trailer area to be cleared before each new load?

Log attached -> 
[log_FS25_111224.txt](https://github.com/user-attachments/files/18096376/log_FS25_111224.txt)

Screenshots attached (p.s. i don't have a screenshot after the 1st reset to show that loading areas got cleared properly after using sellpoint)->

![20241211135504_1](https://github.com/user-attachments/assets/f18d0d83-c2b4-4e71-98e1-c21aba114dfd)
![20241211135629_1](https://github.com/user-attachments/assets/9c4afc6b-4633-4b07-9815-ca7692d8d8e1)
![20241211135852_1](https://github.com/user-attachments/assets/16c5964e-488a-4915-929c-e414998ca62f)

**Comment by loki79uk** [comment] 2024-12-11 18:44
Should be fixed in latest release https://github.com/loki79uk/FS25_UniversalAutoload/releases

I'll look at the double resetting issue separately

**Comment by RobertoNogueir** [comment] 2024-12-11 23:55
> Should be fixed in latest release https://github.com/loki79uk/FS25_UniversalAutoload/releases
> 
> I'll look at the double resetting issue separately

I haven't tested the issue of selling the logs with the tension belts fastened, but I think I had the same problem in version 0.2.0.1, "invisible log in the trailer".
steps to reproduce:
load the trailer with dead trees.
tighten the straps
cut one of the logs inside the trailer with the chainsaw
unload the trailer

It is no longer possible to load the trailer again.
"Unable to load any more Items of this size."

After restarting the game it returned to normal.

thanks for the good work.

**Comment by loki79uk** [comment] 2024-12-12 22:12
Closing original issue as fixed.

@onetaps I couldn't reprodude the double resetting problem (with loading area dissapearing).  Please open a new bug with the minimal steps required to reproduce if it is still happening for you with the latest version.

**Closed by loki79uk** 2024-12-12 22:12 UTC
