### ISSUE TITLE
Does not work on leased machinery

### ISSUE THREAD

**Issue by montyhsmith** [loki79uk/FS25_UniversalAutoload#87] opened 2024-12-05 21:33 UTC
When leasing a vehicle/trailer, autoload does not work at all. There are no button props to load/change settings.

**Comment by loki79uk** [comment] 2024-12-05 21:45
Can you attach your log file please.  It works for me:

![image](https://github.com/user-attachments/assets/f9b556ea-a2ad-4605-83d8-d08db391270e)
![image](https://github.com/user-attachments/assets/3d9b9672-7c7f-45ac-9225-b4403ba94f3d)
![image](https://github.com/user-attachments/assets/45387fda-5862-4091-be93-c1b98d1b47c8)

**Comment by Murkysparks** [comment] 2024-12-06 06:26
can confirm leased krone trailer wont auto load pallets, no debug when Shift Crtl f12
auto loading working on owned krone trailer

**Comment by Murkysparks** [comment] 2024-12-06 06:28
![image_2024-12-06_192820109](https://github.com/user-attachments/assets/5dbe1335-0f08-4af0-bf3c-94d9512726fe)

**Comment by loki79uk** [comment] 2024-12-06 07:59
I believe you already, screenshots are not helpful for fixing anything. Can you please attach your log file as requested, and your settings file too would be helpful.

**Comment by geeknessfr** [comment] 2024-12-06 15:18
@Murkysparks Make sure you have the latest version of the mod, as it seems this is not the case, because you don't have the "Loading Method" option in your Help menu (top left corner) and in debug mode you should also see the ID of the vehicle, like me on my game, actually : 

![image](https://github.com/user-attachments/assets/604f7418-4e85-4450-b235-5162687fee6e)

**Comment by loki79uk** [comment] 2024-12-07 01:07
Closing as can't reproduce.  As stated above, please update to the latest version.

**Closed by loki79uk** 2024-12-07 01:07 UTC
