### ISSUE TITLE
Round Bales on there Side

### ISSUE THREAD

**Issue by ChaseD32c** [loki79uk/FS25_UniversalAutoload#48] opened 2024-12-01 22:31 UTC
Could you please make the round bales have a option to load on there side like Americans load round bales.
![00e0e_by6fPwYTHu8_0hq0dp_600x450](https://github.com/user-attachments/assets/70f05002-585e-450d-8883-2e89251dc6b1)

**Comment by loki79uk** [comment] 2024-12-01 22:34
There is, you just have to select "layer" mode.  There is no keybinding for it by default, but go into keybinding settings and set something.

![image](https://github.com/user-attachments/assets/4953c2c7-d9ee-47ba-af55-619f851541f6)
![image](https://github.com/user-attachments/assets/6117fc8a-b5a4-4f7e-9ba2-d2f4091ddb28)

**Comment by loki79uk** [comment] 2024-12-03 22:27
I forgot about adding the default key until just now.  But it will be in the next release that the default key for horizontal loading is "insert".  Closing as not a bug.

**Closed by loki79uk** 2024-12-03 22:27 UTC
