### ISSUE TITLE
Autoload Added to watertrailer (one Off)

### ISSUE THREAD

**Issue by tricktherick** [loki79uk/FS25_UniversalAutoload#18] opened 2024-11-29 16:02 UTC
adds autoloader to in game and any mods that classify vehicle type="waterTrailer" like the MKS32

**Comment by tricktherick** [comment] 2024-11-29 16:06
Temp work around for modders add a 

   <vehicleTypes>
        <type name="WaterTanker" parent="waterTrailer" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
        </type>
    </vehicleTypes>
    
    in your modDesc and then address your vehicle type as a "WaterTanker"

**Comment by tricktherick** [comment] 2024-11-29 16:07
Temp work around for modders add a
"<vehicleTypes>
        <type name="WaterTanker" parent="waterTrailer" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
        </type>
    </vehicleTypes>"
    in your modDesc and then address your vehicle type as a "WaterTanker"

**Comment by tricktherick** [comment] 2024-11-29 16:08
Temp work around for modders add a

vehicleTypes
type name="WaterTanker" parent="waterTrailer" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua"
/vehicleTypes
in your modDesc and then address your vehicle type as a "WaterTanker"

**Comment by loki79uk** [comment] 2024-11-29 17:04
It shouldn't do unless they have tension belts, but also because I am not filtering by fill types yet:

see: https://github.com/loki79uk/FS25_UniversalAutoload/blob/046b053e7f2622876c17ff53eb85b75f9464d37e/UniversalAutoload.lua#L1257-L1265

**Comment by tricktherick** [comment] 2024-11-29 17:24
Noted Looking further into the cause and trying to replicate why i had a Autoloading Water trailer that does not have tension belts

**Comment by tricktherick** [comment] 2024-11-29 17:37
Cant duplicate dont know what caused it even tried a new save bought the trailers again without mod installed and saved it then came in with mod it does respond with 

![image](https://github.com/user-attachments/assets/60d84db4-0515-41df-b086-14d90d5c91fb)

But does not let me autoload like it did the first time with the in game water tanker so idk close this one i guess

**Comment by tricktherick** [comment] 2024-11-29 23:23
It did it again this time to a tipper
![image](https://github.com/user-attachments/assets/77052655-d237-4051-b95b-0e93ed06da1c)

**Comment by tricktherick** [comment] 2024-11-29 23:24
Tipper does not have tension belts in xml either

**Comment by loki79uk** [comment] 2024-11-29 23:26
What does it say in the log?  I've added more lines about the tension belts and fill types for the next release, but still have some work to do on it.

**Comment by tricktherick** [comment] 2024-11-29 23:42
2024-11-29 17:15 *** UNIVERSAL AUTOLOAD - FOUND NEW OBJECT TYPE: C:/Users/trick/OneDrive/Documents/My Games/FarmingSimulator2025/mods/DTAP_Kick_Vehicles/i3ds/vario1000.i3d ***
2024-11-29 17:15  OBJECT NOT VALID
2024-11-29 17:15 DELETE SHOP VEHICLE: DTAPGAMING DTAP CST 1550 KICK
2024-11-29 17:15 *** UNIVERSAL AUTOLOAD - FOUND NEW OBJECT TYPE: C:/Users/trick/OneDrive/Documents/My Games/FarmingSimulator2025/mods/DTAP_Kick_Vehicles/i3ds/vnx300.i3d ***
2024-11-29 17:15  OBJECT NOT VALID
2024-11-29 17:15 [PowerTools] Warning: Failed to register main key for PowerTools
2024-11-29 17:30 Game saved successfully.
2024-11-29 17:30 [PowerTools] Warning: Failed to register main key for PowerTools
2024-11-29 17:31 C:/Users/trick/OneDrive/Documents/My Games/FarmingSimulator2025/mods/DTAP_Kick_Vehicles/i3ds/conveyAllCST1550.i3d (37.94 ms)
2024-11-29 17:31 data/shared/wheels/tires/continental/contiUrbanHA3/275_70R22_5.i3d (3.14 ms)
2024-11-29 17:31 *** UNSUPPORTED CONFIG - #ALL (UNIQUE) ***
2024-11-29 17:31 CREATE SHOP VEHICLE: DTAPGAMING DTAP CST 1550 KICK
2024-11-29 17:31 *** UNSUPPORTED CONFIG - #ALL (UNIQUE) ***
2024-11-29 17:31 CREATE REAL VEHICLE: DTAPGAMING DTAP CST 1550 KICK
2024-11-29 17:31 SHOP VEHICLE STILL EXISTS 1465081
2024-11-29 17:31 UAL - ON VEHICLE BUY EVENT
2024-11-29 17:31 UAL - SAVE SHOP CONFIGURATION
2024-11-29 17:31 DELETE SHOP VEHICLE: DTAPGAMING DTAP CST 1550 KICK


happened while buying and selling the same trailer while working on adding Clearance lights to the auger im working on
not sure if buying and selling over and over is causing it to happen some times but not others or if its just lag on purchase causing it unfort
![image](https://github.com/user-attachments/assets/698e685a-c906-4edf-90d6-2fe14a334af6)

**Comment by loki79uk** [comment] 2024-12-01 22:54
What were you expecting to happen here?  It is not clear from only the log.

These messages are fine:
- "UNSUPPORTED CONFIG" just means that one of the trailers configurations is not suitable for UAL
- "OBJECT NOT VALID" just means we don't want to load that onto other trailers

**Comment by tricktherick** [comment] 2024-12-02 22:57
Agreed i was not "expecting" anything to happen it put an Autoload on a Non Valid object and UNSUPPORTED CONFIG and you asked for the log which didnt explain why it happened

**Comment by tricktherick** [comment] 2024-12-02 22:59
The bottom part shows it added it 
![image](https://github.com/user-attachments/assets/0da4255b-2f8a-42b0-af3e-f17946242160)

**Comment by loki79uk** [comment] 2024-12-03 08:50
I meant what does it say in the log about tensions belts:
Should be something like: `Salek ANS-1900: UAL - tension belts (2)`

**Comment by tricktherick** [comment] 2024-12-03 16:37
nothing, that was Literally copied from the log starting before the purchase and including 2 previous vehicle purchases during the purchase while in the styling the trailer in the shop and after the purchase where it added the autoloader havent tried again since any of the updates yet though been playing on a server lately with a group on a Struggle map so havent been just randomly buying trailers to see if its still happening.

________________________________

**Comment by loki79uk** [comment] 2024-12-03 21:44
Okay, well you should update if you can because there have been quite few bug fixes.  I also wouldn't recommend using this at all on your important savegames for now, see README:
![image](https://github.com/user-attachments/assets/6bafe5b8-e61d-4a9d-a392-34af16e184f3)

**Comment by loki79uk** [comment] 2024-12-07 00:57
Closing as can't reproduce.  If it happens again, please save your complete log file and attach it to a new bug.

**Closed** 2024-12-07 00:57 UTC
