### ISSUE TITLE
Unable to Load more of that size

### ISSUE THREAD

**Issue by LostJesus** [loki79uk/FS25_UniversalAutoload#82] opened 2024-12-05 01:58 UTC
It seems if you dont unload and sell at certain points the trailer still thinks it loaded.

**Comment by loki79uk** [comment] 2024-12-05 08:30
I thought it must be sell points removing pallets after thinking about it last night from the other bug: https://github.com/loki79uk/FS25_UniversalAutoload/issues/81

I will try to reproduce it today so I can be sure the fix is working.

loadedObjects must not be reset or the following is not toggling properly, because it should reset the loading when that is empty:

```lua
	if totalUnloadCount == 0 then
		if not spec.noLoadedObjects then
			spec.noLoadedObjects = true
			-- print("NO OBJECTS TO UNLOAD..")
			UniversalAutoload.resetLoadingArea(self)
			UniversalAutoload.updateActionEventText(self)
		end
	else
		if spec.noLoadedObjects then
			spec.noLoadedObjects = false
			-- print("FOUND LOADED OBJECTS..")
			UniversalAutoload.updateActionEventText(self)
		end
	end
```

**Comment by loki79uk** [comment] 2024-12-07 01:06
Has this happened to you anymore?  If you can find a way to reproduce it (with a certain vehicle or sell point) then please let me know!

**Comment by LostJesus** [comment] 2024-12-07 01:38
it hasnt happened but i was just unloading them i will try to reprodue it and let you know!

**Comment by bahl33ted** [comment] 2024-12-08 03:15
Getting this error on update 17. I was able to load a trailer full of lettuce. Sold it and then tried to load it again and I get this error "Unable to load any more items of this size" . I'm not using any filters and have it set to stacked. I tried unload and load again but it just repeats the error. I unhitched the trailer and tried again. Same error. Going to downgrade to update 15 and see if that fixes it.

**Comment by bahl33ted** [comment] 2024-12-08 06:25
FYI Downgrading fixed the issue for me.

**Comment by loki79uk** [comment] 2024-12-08 14:24
Can you try with the latest version and send me your log file please.

**Comment by loki79uk** [comment] 2024-12-11 19:24
I think this is a duplicate of bug https://github.com/loki79uk/FS25_UniversalAutoload/issues/108 - so if correct then the issue only happened if you went fast enough when driving to the sell point. Hopefully fixed now in latest versions. https://github.com/loki79uk/FS25_UniversalAutoload/releases

I think it could still happen if you have the straps unstrapped, and manage to go fast enough without the load falling off anyway..

**Closed by loki79uk** 2024-12-11 19:24 UTC
