### ISSUE TITLE
Autoload on Lizard truck

### ISSUE THREAD

**Issue by PietroAlieri** [loki79uk/FS25_UniversalAutoload#156] opened 2024-12-18 10:42 UTC
Hi, 

I'm experiencing problems with the autoload when trying to load on de Lizard truck flatbed. 
It worked in the beginning but now it seems to try and load pallets and bales into the cabin of the truck.

**Comment by loki79uk** [comment] 2024-12-18 10:45
Probably this: https://github.com/loki79uk/FS25_UniversalAutoload/issues/21

Try removing all of the old configurations and buy them again.

**Comment by loki79uk** [comment] 2024-12-20 19:01
Closing as not a bug, but you can continue to message on here if the above didn't work.

**Closed by loki79uk** 2024-12-20 19:01 UTC
