### ISSUE TITLE
Game saving game issue with 0.0.9 

### ISSUE THREAD

**Issue by Hillcow68** [loki79uk/FS25_UniversalAutoload#57] opened 2024-12-02 14:21 UTC
hello,

I  downloaded version 0.0.9, started up a new game with only universalautoload as mod installed. saved the game and is still saving the game.
then i tried it with version 0.0.8 same issue.
with 0.0.7 no issue.
added the used savegame (4)

[savegame4.zip](https://github.com/user-attachments/files/17979140/savegame4.zip)

kind regards,

Hillcow

**Comment by geeknessfr** [comment] 2024-12-02 16:08
I played on 2 different saves and had no issue to save my games...

Maybe you could share the log.txt file when you try to save, so we can see what is not working ?

**Comment by loki79uk** [comment] 2024-12-02 17:14
That is odd, the savegame looks correct for the UAL stuff:
![image](https://github.com/user-attachments/assets/bbad4f4b-1255-454d-a383-c82398c13918)
![image](https://github.com/user-attachments/assets/d1b4c9b3-90b1-4b24-98ec-9c7ab63df054)

Can you attach your log file from when it wouldn't save?

**Comment by morpheus0815** [comment] 2024-12-03 07:44
Hello loki79uk, 
the same issue applies in our Mulitplayer Savegame. Since we have added V.0.0.0.9 after bootup of the server it raises an LUA error "SetCompleteSaving". This turns in an endless saving loop and the game will not saved anymore. 


As far as I get access to the repective log files. I will add them for further analysis.

**Comment by loki79uk** [comment] 2024-12-03 09:47
Thanks for the description.  It doesn't make much sense, but I'll try to reproduce it.  All I am doing for save is:
https://github.com/loki79uk/FS25_UniversalAutoload/blob/961e6e23b42bbaee24f09065158cc493a633c776/UniversalAutoload.lua#L1665-L1685

So I'm not sure where a '%' charachter could come from..

Is it just that savegame?  can you try a new one too?

**Comment by morpheus0815** [comment] 2024-12-03 10:01
I just created an new savegame from nothing for the Riverbend. only this script is added as mod and the error still appear. Running on Nitrado.

```
2024-12-03 10:59 Error: Running LUA method 'onSaveStartComplete'.
dataS/scripts/xml/XMLFile.lua:537: invalid use of '%' in replacement string
```

I can not provide this savegame as I can't inital save it.

**Comment by loki79uk** [comment] 2024-12-03 10:13
I just loaded an existing game on dedicated server, joined, logged in as admin, saved:
```
dataS/character/playerF/shoes/sneaker01.i3d (1.74 ms)
Server (1) joined the game
dataS/character/playerM/heads/mHead01.i3d (127.30 ms)
UAL Player.writeStream
UAL Player.writeStream
connectedToDedicatedServer: true
dataS/character/playerF/pants/botYogaPants.i3d (7.15 ms)
dataS/character/playerF/heads/fHead02.i3d (69.12 ms)
dataS/character/playerF/shirts/topTankTop.i3d (32.95 ms)
dataS/character/playerF/shoes/sportSneaker.i3d (63.72 ms)
dataS/character/playerF/hairStyles/hairStyleLongSideParted.i3d (21.77 ms)
UAL - ON WRITE STREAM
UAL - ON WRITE STREAM
UAL - ON WRITE STREAM
UAL - ON WRITE STREAM
UAL - ON WRITE STREAM
UAL - ON WRITE STREAM
Game saved successfully.
```

Can't look at this anymore until this evening, but it is even weirder if it works for you with older versions and not the latest..

**Comment by morpheus0815** [comment] 2024-12-03 10:17
> I just loaded an existing game on dedicated server, joined, logged in as admin, saved:
> 
> ```
> dataS/character/playerF/shoes/sneaker01.i3d (1.74 ms)
> Server (1) joined the game
> dataS/character/playerM/heads/mHead01.i3d (127.30 ms)
> UAL Player.writeStream
> UAL Player.writeStream
> connectedToDedicatedServer: true
> dataS/character/playerF/pants/botYogaPants.i3d (7.15 ms)
> dataS/character/playerF/heads/fHead02.i3d (69.12 ms)
> dataS/character/playerF/shirts/topTankTop.i3d (32.95 ms)
> dataS/character/playerF/shoes/sportSneaker.i3d (63.72 ms)
> dataS/character/playerF/hairStyles/hairStyleLongSideParted.i3d (21.77 ms)
> UAL - ON WRITE STREAM
> UAL - ON WRITE STREAM
> UAL - ON WRITE STREAM
> UAL - ON WRITE STREAM
> UAL - ON WRITE STREAM
> UAL - ON WRITE STREAM
> Game saved successfully.
> ```
> 
> Can't look at this anymore until this evening, but it is even weirder if it works for you with older versions and not the latest..

Ok don't hurry ;-)  I'll try an older version. Just let me know if you need further information to support your work.

**Comment by geeknessfr** [comment] 2024-12-03 13:20
Hey,

I just tested it on a Nitrado server, and I don’t have the issue. You can see it in this log:

```
2024-12-03 14:06 Geekness joined the game
2024-12-03 14:06 UAL Player.writeStream
2024-12-03 14:06 UAL Player.writeStream
2024-12-03 14:06 connectedToDedicatedServer: true
2024-12-03 14:06 UAL - ON WRITE STREAM
2024-12-03 14:06 UAL - ON WRITE STREAM
2024-12-03 14:06 UAL - ON WRITE STREAM
2024-12-03 14:06 UAL - ON WRITE STREAM
2024-12-03 14:06 UAL - ON WRITE STREAM
2024-12-03 14:07 Game saved successfully.
2024-12-03 14:08 Game saved successfully.
```

I tried loading your savegame on the dedicated server (Nitrado), and same result—no issue.

Did you (or could you) try uploading your "savegame4" to a new slot on Nitrado using the FS25 Admin Panel? Don’t put any name, just upload the file, stop the server, select the slot you used, and restart the server. Then, go in-game, log in as admin, and try saving.

I just want to know if, when doing exactly the same steps as me, it works or not. Oh, and did you try restarting the server? This time, from the Nitrado panel, restarting the whole server.

**Comment by morpheus0815** [comment] 2024-12-03 14:08
> Hey,
> 
> I just tested it on a Nitrado server, and I don’t have the issue. You can see it in this log:
> 
> ```
> 2024-12-03 14:06 Geekness joined the game
> 2024-12-03 14:06 UAL Player.writeStream
> 2024-12-03 14:06 UAL Player.writeStream
> 2024-12-03 14:06 connectedToDedicatedServer: true
> 2024-12-03 14:06 UAL - ON WRITE STREAM
> 2024-12-03 14:06 UAL - ON WRITE STREAM
> 2024-12-03 14:06 UAL - ON WRITE STREAM
> 2024-12-03 14:06 UAL - ON WRITE STREAM
> 2024-12-03 14:06 UAL - ON WRITE STREAM
> 2024-12-03 14:07 Game saved successfully.
> 2024-12-03 14:08 Game saved successfully.
> ```
> 
> I tried loading your savegame on the dedicated server (Nitrado), and same result—no issue.
> 
> Did you (or could you) try uploading your "savegame4" to a new slot on Nitrado using the FS25 Admin Panel? Don’t put any name, just upload the file, stop the server, select the slot you used, and restart the server. Then, go in-game, log in as admin, and try saving.
> 
> I just want to know if, when doing exactly the same steps as me, it works or not. Oh, and did you try restarting the server? This time, from the Nitrado panel, restarting the whole server.
> 
> EDIT :
> 
> Oh, I missed something...
> 
> You said: "the same issue applies in our Multiplayer Savegame."
> 
> Does that mean you’re also getting the error in a local game?
> 
> If yes, could you try temporarily removing (keep it anywhere else) the "UniversalAutoload.xml" file from your "Documents\My Games\FarmingSimulator2025\modSettings" then reload your game completely and try saving again ? (in local, then in MP)




Hello geeknessfr, 
the initial issue report was not from me. So I can not provide the savegame4. We are 2 different persons & groups having this issue. 

For me the issue appeared in your current Multiplayer game and also tested when I starting a new game on Slot 2 using Nitrado Web/Interface. And adding just this mod. The error appears by clicking the Save button in game.  
We were restarting the gaming Server and also the Nitrado server without any impact on the issue.
Also I currently test it in a new started single player. Only the script has been activated. The same error appears. 
The UniversalAutoload.xml does not exists in my modSettings on the local maschine. So can not be removed. only "LumberJack.xml" is available. BTW LumberJack I have not downloaded. ;-)

**Comment by morpheus0815** [comment] 2024-12-03 14:14
Updating to  V0.0.1.0 error still appear

**Comment by loki79uk** [comment] 2024-12-03 14:20
> For me the issue appeared in your current Multiplayer game and also tested when I starting a new game on Slot 2 using Nitrado Web/Interface. And adding just this mod. The error appears by clicking the Save button in game. We were restarting the gaming Server and also the Nitrado server without any impact on the issue. Also I currently test it in a new started single player. Only the script has been activated. The same error appears. The UniversalAutoload.xml does not exists in my modSettings on the local maschine. So can not be removed. only "LumberJack.xml" is available. BTW LumberJack I have not downloaded. ;-)

Can you please attach the full log file for this single player game.  There is no way that `LumberJack.xml` can exisit without you having had the mod installed at some point (or else you created it yourself!)

**Comment by morpheus0815** [comment] 2024-12-03 14:32
> Can you please attach the full log file for this single player game. There is no way that `LumberJack.xml` can exist without you having had the mod installed at some point (or else you created it yourself!)

How to extract the log file. It stucks in an endless loading screen. See attached screenshot. 
LumberJack was only installed on FS22 and never the added to FS25 from my side. Thats also what's confused me. 
<img width="1448" alt="image" src="https://github.com/user-attachments/assets/3e42e395-96b7-41ac-8c77-19bfb8cca8a4">

**Comment by geeknessfr** [comment] 2024-12-03 14:34
> How to extract the log file. It stucks in an endless loading screen. See attached screenshot. LumberJack was only installed on FS22 and never the added to FS25 from my side. Thats also what's confused me. 

The log file is in `Documents\My Games\FarmingSimulator2025` called log.txt :
![image](https://github.com/user-attachments/assets/130f5b3c-d2d0-469f-9b05-9e983d50c208)

**Comment by morpheus0815** [comment] 2024-12-03 14:40
> Can you please attach the full log file for this single player game. There is no way that `LumberJack.xml` can exist without you having had the mod installed at some point (or else you created it yourself!)


[log.txt](https://github.com/user-attachments/files/17994610/log.txt)

**Comment by loki79uk** [comment] 2024-12-03 14:49
Thi s could be because you renamed the mod zip file.  Can you try renaming it back to the standard name please?  If it is that then I can make a fix to allow for it.

**Comment by loki79uk** [comment] 2024-12-03 21:14
Closing as fixed.

I have replaced the hard coded xml key strings with the g_currentModName, but I still don't reccommend renaming the mod zip file, since that name is used to write vehicle settings into the savegame by GIANTS.

**Closed by loki79uk** 2024-12-03 21:14 UTC
