### ISSUE TITLE
Unload bales issue when unloading on sale point by unleashing straps 

### ISSUE THREAD

**Issue by LanWolf** [loki79uk/FS25_UniversalAutoload#138] opened 2024-12-15 13:41 UTC
When unloading  bales when unloading on sale point (animal,dealer in river bend) by unleashing straps makes autoload believe the bales are not unloaded.  After I unloaded by releasing straps when standing in the sale point for bales, next load of bales refused to autoload with the error like “no more bales of this size can be loaded” 
After exiting and reloading the savegame (without savings it worked normal again.

**Comment by loki79uk** [comment] 2024-12-15 14:01
Okay, thanks - It sounds like I'll have to do the same thing that I did with logs and check for items being deleted by the game.  It is strange that this doesn't happen with pallets though..

**Comment by LanWolf** [comment] 2024-12-15 14:43
Might be different behavior for trailers that come from other sources, not giants. This was the 20ft old bale trailer from 4d modding on itch.io

**Comment by geeknessfr** [comment] 2024-12-15 19:31
> just a little sideways thinking, does this also happen with not complet filled egg or honey pellets ?

There is a filter to load Only Full Pallets ... Look at the help keys (top left corner) ... you'll find it...

**Comment by LanWolf** [comment] 2024-12-15 19:55
> > just a little sideways thinking, does this also happen with not complet filled egg or honey pellets ?
> 
> There is a filter to load Only Full Pallets ... Look at the help keys (top left corner) ... you'll find it...

I know the filter, it was just a heads up to Loki to double check that behavior on not full pallets.  I think this happened once to me when loading half a pallet of eggs on the kubota and unloading them into the small production point.

**Comment by geeknessfr** [comment] 2024-12-15 20:05
I just tested with the same trailer (20ft Bale Trailer "Old" from 4D Modelling) but it worked perfectly for me :

- Autoloading Bales in a "field" (CTRL-SHIFT-R)
- Going to Animal dealder
- Unbelts the bales and selling them
- Returned to the field
- Tried with Bale autoload and also with manual autoload (I mean.. CTRL-SHIFT-R and SHIFT-R)
- Bales jumped on my trailer.

I also tried manually... and as we couldn't sell them without unstrapping them... the script saw them unloaded.


Could you share your log.txt file please ?
And it's on a local game or on a dedicated server ?


Some screenshots of my tests :

![image](https://github.com/user-attachments/assets/6f52010c-5c6d-4b62-92d8-a72c21767d40)
![image](https://github.com/user-attachments/assets/d9681a42-fe2b-42e1-853e-66d9b1280039)
![image](https://github.com/user-attachments/assets/89824372-c380-4541-9afe-4a774c72e5e1)

**Comment by loki79uk** [comment] 2024-12-15 21:29
@LanWolf What version are you using?

**Comment by LanWolf** [comment] 2024-12-16 16:17
i think it was one of the first 0.2 versions, i updated since then to now to 0.2.14 and tried if i could recreate the behaviour, but for now it seems to work well.
It was on a local game.

**Comment by loki79uk** [comment] 2024-12-16 16:19
Closing as can't reproduce / already fixed

**Closed by loki79uk** 2024-12-16 16:19 UTC
