### ISSUE TITLE
Bug Report – Universal Autoload Mod Causing Server Issues

### ISSUE THREAD

**Issue by FreestyleBasti** [loki79uk/FS25_UniversalAutoload#135] opened 2024-12-14 18:06 UTC
Dear Mod Creator,

I am reaching out to report an issue related to the Universal Autoload mod in Farming Simulator 2025 (FS 25) that I encountered on my dedicated server.
Problem Description:

When the Universal Autoload mod is active on my server, players experience repeated disconnections. The following error messages appear in the logs:

**UAL Player.writeStream
connectedToDedicatedServer: true
UAL - ON WRITE STREAM <number>**

Additionally, the server logs show recurring OpenSSL errors, such as:
**openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify**

Disabling the Universal Autoload mod resolves the issue.

**Technical Details:**

- Game Version: Farming Simulator 2025 (latest version)
- Server: Dedicated Windows Server
- Other Mods Installed: Various, including map and vehicle mods (details available upon request)
    
**Logs:**
-  Server logs contain the OpenSSL errors mentioned above when the mod is active.
- The log.txt file from the game shows repeated writeStream messages.

**Steps to Reproduce:**

- Install the mod on a dedicated server.
- Start a game and allow players to join.
- Players are disconnected after a short period, and the errors are logged.

**Request for Investigation:**

I kindly ask you to look into this issue, particularly regarding:

- Network communication (e.g., writeStream process)
- Compatibility of the mod with the latest version of FS 25

Thank you for your hard work on the Universal Autoload mod! I really appreciate your efforts and look forward to a potential fix or update in the future.

Best regards,
Sebastian (FreestyleBasti)

**Comment by loki79uk** [comment] 2024-12-14 18:10
You should get one write stream message for each vehicle.  I will add a new debugging print in the next release to narrow down which one it is.

**Comment by FreestyleBasti** [comment] 2024-12-14 21:04
[log_2024-12-14_18-48-23_game.txt](https://github.com/user-attachments/files/18137700/log_2024-12-14_18-48-23_game.txt)
[log_2024-12-14_18-48-23_server.txt](https://github.com/user-attachments/files/18137698/log_2024-12-14_18-48-23_server.txt)

**Comment by Selyria** [comment] 2024-12-14 21:14
We have the same map and also the autoloader on the same version and there are no OpenSSL errors.

**Comment by loki79uk** [comment] 2024-12-14 21:27
It might be related to whatever wrote the last line in the log:
```2024-12-14 18:50  disable spot: no trees found```

**Comment by FreestyleBasti** [comment] 2024-12-14 22:31
![Screenshot 2024-12-14 232954](https://github.com/user-attachments/assets/7a26037f-6896-4815-8752-2eadfc9af7b7)
these are our active mods

**Comment by loki79uk** [comment] 2024-12-14 22:39
I'd try without the kingmods one maybe - not sure what else would talk about "spots" and "trees"

**Comment by loki79uk** [comment] 2024-12-14 22:49
Otherwise use a utility that can search inside zips (such as TotalCommander) and search for the strings "disable spot" or "no trees found"

**Comment by FreestyleBasti** [comment] 2024-12-14 23:42
I deactivated the "kingmods" Mod, and it works. I Don't have Network issues. But My console says:
[14/Dec/2024:20:00:08] Error: Socket error when sending HTTP response - Unknown error (0)

[14/Dec/2024:22:00:49] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:22:00:49] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:22:00:49] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:22:00:49] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:22:00:49] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:30:18] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:30:18] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:30:18] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:30:18] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:30:18] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:30:18] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:30:18] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:58:40] Game server process stopped
[14/Dec/2024:23:58:41] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:58:41] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:58:41] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:58:41] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:58:41] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:58:41] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:58:41] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[14/Dec/2024:23:59:04] Uploaded mod 'FS25_ContractBoost.zip' to 'C:/Users/EclairBear/Documents/My Games/FarmingSimulator2025/mods/FS25_ContractBoost.zip'
[14/Dec/2024:23:59:10] Mod 'C:/Users/EclairBear/Documents/My Games/FarmingSimulator2025/mods/FS25_SmallWorkshop.zip' deleted
[14/Dec/2024:23:59:25] Game server process started
[14/Dec/2024:23:59:25] Game server started
[15/Dec/2024:00:00:01] Automatic game server restart
[15/Dec/2024:00:00:01] Game server process stopped
[15/Dec/2024:00:00:01] Game server process started
[15/Dec/2024:00:36:53] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[15/Dec/2024:00:36:53] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[15/Dec/2024:00:36:53] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[15/Dec/2024:00:36:53] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[15/Dec/2024:00:36:53] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
[15/Dec/2024:00:36:53] openssl error (336150819): error:14094123:SSL routines:ssl3_read_bytes:application data after close notify




And

2024-12-15 00:01 data/handTools/brandless/flashlight/flashlight.i3d (59.68 ms)
2024-12-15 00:01 dataS/character/playerM/heads/mHead01.i3d (190.24 ms)
2024-12-15 00:31 Game saved successfully.
2024-12-15 00:36 Sebb joined the game
2024-12-15 00:36 dataS/character/playerM/fullBody/strauss/motion2020PantsVariant2ndVariant.i3d (113.86 ms)
2024-12-15 00:36 dataS/character/playerM/heads/mHead02.i3d (9.79 ms)
2024-12-15 00:36 dataS/character/playerM/gloves/strauss/glovesEsTrailLight02.i3d (51.62 ms)
2024-12-15 00:36 dataS/character/playerM/attachments/headgearCowboy.i3d (11.91 ms)
2024-12-15 00:36 dataS/character/playerM/attachments/glassesSports02.i3d (0.97 ms)
2024-12-15 00:36 dataS/character/playerM/facialHair/mHead02/goatee01.i3d (23.13 ms)
2024-12-15 00:37 UAL Player.writeStream
2024-12-15 00:37 UAL Player.writeStream
2024-12-15 00:37 connectedToDedicatedServer: true
2024-12-15 00:37 dataS/character/playerM/jacket/topDenimJacket.i3d (27.30 ms)
2024-12-15 00:37 dataS/character/playerM/hairStyles/hairStyleMidParted01.i3d (37.18 ms)
2024-12-15 00:37 dataS/character/playerM/facialHair/mHead01/beardStubble.i3d (1.53 ms)
2024-12-15 00:37 UAL - ON WRITE STREAM 345154
2024-12-15 00:37 UAL - ON WRITE STREAM 346072
2024-12-15 00:37 UAL - ON WRITE STREAM 346310
2024-12-15 00:37 UAL - ON WRITE STREAM 349271
2024-12-15 00:37 UAL - ON WRITE STREAM 357441
2024-12-15 00:38 Game saved successfully.
2024-12-15 00:38 Warning: Send called with unknown target address.
2024-12-15 00:38 Sebb left the game

**Comment by loki79uk** [comment] 2024-12-16 23:29
Have you got any further in figuring out what is causing these SSL errors?  It is not something I've ever seen before.

**Comment by loki79uk** [comment] 2024-12-18 12:13
It looks like a GIANTS problem, or at least that it is not a UAL problem:  https://forum.giants-software.com/viewtopic.php?t=202179

Closing as not a bug.

**Closed by loki79uk** 2024-12-18 12:13 UTC

**Comment by SETKA-SIMULATORS** [comment] 2025-02-26 11:43
Hello, what we noticed on our dedicated server is that when using the autoload to collect the logs, the jerks and jumps begin and it is impossible to play until those logs are sold. The FPS and milliseconds of the connection are not altered. We have tried moving the logs by loading them manually and that does not happen. Only when we load them using autoload. Greetings and thank you very much for your mod and time spent on it.

**Comment by loki79uk** [comment] 2025-02-26 12:30
> Hello, what we noticed on our dedicated server is that when using the autoload to collect the logs, the jerks and jumps begin and it is impossible to play until those logs are sold. The FPS and milliseconds of the connection are not altered. We have tried moving the logs by loading them manually and that does not happen. Only when we load them using autoload. Greetings and thank you very much for your mod and time spent on it.

What spec is your server? Can you attach a log file from when it is happening?

**Comment by SETKA-SIMULATORS** [comment] 2025-02-27 14:29
Hi, what do you mean by What spec is your server? We have a Gportal server for 8 players

**Comment by loki79uk** [comment] 2025-02-28 10:47
I don't think it is possible to attach files properly via email.  Use the web interface and you can attach files by copy/pate, drag/drop or using the add file dialog.
