### ISSUE TITLE
Controller on PC issue

### ISSUE THREAD

**Issue by MohammadAkthamObeidat** [loki79uk/FS25_UniversalAutoload#80] opened 2024-12-04 22:33 UTC
I play using an Xbox Series X controller on a PC, and the RB & LB buttons do not work after adding the mod.

**Comment by loki79uk** [comment] 2024-12-04 23:12
What are those buttons bound to?  Could it be related to the base game issue when too many key bindings are created?

For example with this vehicle (that has R to unload) I do not get the "toggle load side" command because the maximum number of key bindings is reached:
![image](https://github.com/user-attachments/assets/99643096-89fa-44e4-9e5f-dc2f15faccc2)

**Comment by geeknessfr** [comment] 2024-12-04 23:57
The LB & RB buttons are the modifiers on a controller, like left click & right click on the mouse.

But I can confirm that the buttons still work with the latest version of the mod for me : 
![image](https://github.com/user-attachments/assets/2fdada4a-6b77-4f67-af89-38b8747b89fb)

**Comment by loki79uk** [comment] 2024-12-06 00:55
Closing as not a bug.  If you still have trouble with key bindings, then try resetting to defaults.

**Closed by loki79uk** 2024-12-06 00:55 UTC
